package com.test.vo.entity;

import com.wave.base.vo.BaseVo;
import java.io.Serializable;

public class JOrgInfo extends BaseVo implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.org_id
	 * @mbg.generated
	 */
	private String orgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.org_type
	 * @mbg.generated
	 */
	private String orgType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.area_code
	 * @mbg.generated
	 */
	private String areaCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.parent_org_id
	 * @mbg.generated
	 */
	private String parentOrgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.sort_serial_no
	 * @mbg.generated
	 */
	private Integer sortSerialNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.org_encode
	 * @mbg.generated
	 */
	private String orgEncode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.org_name
	 * @mbg.generated
	 */
	private String orgName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.org_name_py
	 * @mbg.generated
	 */
	private String orgNamePy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.other_name
	 * @mbg.generated
	 */
	private String otherName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.other_name_py
	 * @mbg.generated
	 */
	private String otherNamePy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.org_short_name
	 * @mbg.generated
	 */
	private String orgShortName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.org_property_id
	 * @mbg.generated
	 */
	private String orgPropertyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.org_short_name_py
	 * @mbg.generated
	 */
	private String orgShortNamePy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.system_type_id
	 * @mbg.generated
	 */
	private String systemTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.org_level_id
	 * @mbg.generated
	 */
	private String orgLevelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.org_category_id
	 * @mbg.generated
	 */
	private String orgCategoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.org_category_sub_id
	 * @mbg.generated
	 */
	private String orgCategorySubId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.department_id
	 * @mbg.generated
	 */
	private String departmentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.Industry_class_sub_id
	 * @mbg.generated
	 */
	private String industryClassSubId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.Industry_class_id
	 * @mbg.generated
	 */
	private String industryClassId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.org_attr_id
	 * @mbg.generated
	 */
	private String orgAttrId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.org_sort_id
	 * @mbg.generated
	 */
	private String orgSortId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.org_sort_sub_id
	 * @mbg.generated
	 */
	private String orgSortSubId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.outlay_shape_id
	 * @mbg.generated
	 */
	private String outlayShapeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.finance_budget_code
	 * @mbg.generated
	 */
	private String financeBudgetCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.is_public
	 * @mbg.generated
	 */
	private String isPublic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.is_development_area_org
	 * @mbg.generated
	 */
	private String isDevelopmentAreaOrg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.cangong_piwen
	 * @mbg.generated
	 */
	private String cangongPiwen;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.establishment_date
	 * @mbg.generated
	 */
	private String establishmentDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.telphone
	 * @mbg.generated
	 */
	private String telphone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.post_code
	 * @mbg.generated
	 */
	private String postCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.domain_zh
	 * @mbg.generated
	 */
	private String domainZh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.domain_en
	 * @mbg.generated
	 */
	private String domainEn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.address
	 * @mbg.generated
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.remark
	 * @mbg.generated
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.org_code
	 * @mbg.generated
	 */
	private String orgCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.legal_person_certificate_no
	 * @mbg.generated
	 */
	private String legalPersonCertificateNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.cangong_status
	 * @mbg.generated
	 */
	private Short cangongStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.org_main_obligation_id
	 * @mbg.generated
	 */
	private String orgMainObligationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.inner_org_count
	 * @mbg.generated
	 */
	private Integer innerOrgCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.other_org_count
	 * @mbg.generated
	 */
	private Integer otherOrgCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.xz_qebk_count
	 * @mbg.generated
	 */
	private Integer xzQebkCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.gq_cebt_count
	 * @mbg.generated
	 */
	private Integer gqCebtCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.other_zszz_count
	 * @mbg.generated
	 */
	private Integer otherZszzCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.dept_leader_count
	 * @mbg.generated
	 */
	private Integer deptLeaderCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.dept_leader_high_count
	 * @mbg.generated
	 */
	private Integer deptLeaderHighCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.dept_vice_lead_count
	 * @mbg.generated
	 */
	private Integer deptViceLeadCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.dept_vice_lead_high_count
	 * @mbg.generated
	 */
	private Integer deptViceLeadHighCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.inspect_discipline_count
	 * @mbg.generated
	 */
	private Integer inspectDisciplineCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.other_count
	 * @mbg.generated
	 */
	private Integer otherCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.inner_leader_count
	 * @mbg.generated
	 */
	private Integer innerLeaderCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.inner_leader_high_count
	 * @mbg.generated
	 */
	private Integer innerLeaderHighCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.inner_vice_lead_count
	 * @mbg.generated
	 */
	private Integer innerViceLeadCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.inner_vice_lead_high_count
	 * @mbg.generated
	 */
	private Integer innerViceLeadHighCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.dept_not_leader_count
	 * @mbg.generated
	 */
	private Integer deptNotLeaderCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.dept_not_vice_lead_count
	 * @mbg.generated
	 */
	private Integer deptNotViceLeadCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.inner_not_lead_count
	 * @mbg.generated
	 */
	private Integer innerNotLeadCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.inner_not_vice_lead_count
	 * @mbg.generated
	 */
	private Integer innerNotViceLeadCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.manager_count
	 * @mbg.generated
	 */
	private Integer managerCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.professional_skill_count
	 * @mbg.generated
	 */
	private Integer professionalSkillCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.gongqing_skill_count
	 * @mbg.generated
	 */
	private Integer gongqingSkillCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.special_count
	 * @mbg.generated
	 */
	private Integer specialCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.piwen_id
	 * @mbg.generated
	 */
	private String piwenId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.pw_code
	 * @mbg.generated
	 */
	private String pwCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.status
	 * @mbg.generated
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.createtime
	 * @mbg.generated
	 */
	private String createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.SBJFZ
	 * @mbg.generated
	 */
	private Integer sbjfz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.TJJZZ
	 * @mbg.generated
	 */
	private Integer tjjzz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.TJJFZ
	 * @mbg.generated
	 */
	private Integer tjjfz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.XCJZZ
	 * @mbg.generated
	 */
	private Integer xcjzz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.XCJFZ
	 * @mbg.generated
	 */
	private Integer xcjfz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.XKJZZ
	 * @mbg.generated
	 */
	private Integer xkjzz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.XKJFZ
	 * @mbg.generated
	 */
	private Integer xkjfz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.GJZZ
	 * @mbg.generated
	 */
	private Integer gjzz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.GJFZ
	 * @mbg.generated
	 */
	private Integer gjfz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.WDJ
	 * @mbg.generated
	 */
	private Integer wdj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.QT
	 * @mbg.generated
	 */
	private Integer qt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.XSY
	 * @mbg.generated
	 */
	private Integer xsy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.FXSY
	 * @mbg.generated
	 */
	private Integer fxsy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.DYY
	 * @mbg.generated
	 */
	private Integer dyy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.FDYY
	 * @mbg.generated
	 */
	private Integer fdyy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.ZRKY
	 * @mbg.generated
	 */
	private Integer zrky;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.FZRKY
	 * @mbg.generated
	 */
	private Integer fzrky;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column j_org_info.approval_status
	 * @mbg.generated
	 */
	private String approvalStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table j_org_info
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 4934676238107849831L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.org_id
	 * @return  the value of j_org_info.org_id
	 * @mbg.generated
	 */
	public String getOrgId() {
		return orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.org_id
	 * @param orgId  the value for j_org_info.org_id
	 * @mbg.generated
	 */
	public void setOrgId(String orgId) {
		this.orgId = orgId == null ? null : orgId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.org_type
	 * @return  the value of j_org_info.org_type
	 * @mbg.generated
	 */
	public String getOrgType() {
		return orgType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.org_type
	 * @param orgType  the value for j_org_info.org_type
	 * @mbg.generated
	 */
	public void setOrgType(String orgType) {
		this.orgType = orgType == null ? null : orgType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.area_code
	 * @return  the value of j_org_info.area_code
	 * @mbg.generated
	 */
	public String getAreaCode() {
		return areaCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.area_code
	 * @param areaCode  the value for j_org_info.area_code
	 * @mbg.generated
	 */
	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode == null ? null : areaCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.parent_org_id
	 * @return  the value of j_org_info.parent_org_id
	 * @mbg.generated
	 */
	public String getParentOrgId() {
		return parentOrgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.parent_org_id
	 * @param parentOrgId  the value for j_org_info.parent_org_id
	 * @mbg.generated
	 */
	public void setParentOrgId(String parentOrgId) {
		this.parentOrgId = parentOrgId == null ? null : parentOrgId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.sort_serial_no
	 * @return  the value of j_org_info.sort_serial_no
	 * @mbg.generated
	 */
	public Integer getSortSerialNo() {
		return sortSerialNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.sort_serial_no
	 * @param sortSerialNo  the value for j_org_info.sort_serial_no
	 * @mbg.generated
	 */
	public void setSortSerialNo(Integer sortSerialNo) {
		this.sortSerialNo = sortSerialNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.org_encode
	 * @return  the value of j_org_info.org_encode
	 * @mbg.generated
	 */
	public String getOrgEncode() {
		return orgEncode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.org_encode
	 * @param orgEncode  the value for j_org_info.org_encode
	 * @mbg.generated
	 */
	public void setOrgEncode(String orgEncode) {
		this.orgEncode = orgEncode == null ? null : orgEncode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.org_name
	 * @return  the value of j_org_info.org_name
	 * @mbg.generated
	 */
	public String getOrgName() {
		return orgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.org_name
	 * @param orgName  the value for j_org_info.org_name
	 * @mbg.generated
	 */
	public void setOrgName(String orgName) {
		this.orgName = orgName == null ? null : orgName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.org_name_py
	 * @return  the value of j_org_info.org_name_py
	 * @mbg.generated
	 */
	public String getOrgNamePy() {
		return orgNamePy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.org_name_py
	 * @param orgNamePy  the value for j_org_info.org_name_py
	 * @mbg.generated
	 */
	public void setOrgNamePy(String orgNamePy) {
		this.orgNamePy = orgNamePy == null ? null : orgNamePy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.other_name
	 * @return  the value of j_org_info.other_name
	 * @mbg.generated
	 */
	public String getOtherName() {
		return otherName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.other_name
	 * @param otherName  the value for j_org_info.other_name
	 * @mbg.generated
	 */
	public void setOtherName(String otherName) {
		this.otherName = otherName == null ? null : otherName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.other_name_py
	 * @return  the value of j_org_info.other_name_py
	 * @mbg.generated
	 */
	public String getOtherNamePy() {
		return otherNamePy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.other_name_py
	 * @param otherNamePy  the value for j_org_info.other_name_py
	 * @mbg.generated
	 */
	public void setOtherNamePy(String otherNamePy) {
		this.otherNamePy = otherNamePy == null ? null : otherNamePy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.org_short_name
	 * @return  the value of j_org_info.org_short_name
	 * @mbg.generated
	 */
	public String getOrgShortName() {
		return orgShortName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.org_short_name
	 * @param orgShortName  the value for j_org_info.org_short_name
	 * @mbg.generated
	 */
	public void setOrgShortName(String orgShortName) {
		this.orgShortName = orgShortName == null ? null : orgShortName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.org_property_id
	 * @return  the value of j_org_info.org_property_id
	 * @mbg.generated
	 */
	public String getOrgPropertyId() {
		return orgPropertyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.org_property_id
	 * @param orgPropertyId  the value for j_org_info.org_property_id
	 * @mbg.generated
	 */
	public void setOrgPropertyId(String orgPropertyId) {
		this.orgPropertyId = orgPropertyId == null ? null : orgPropertyId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.org_short_name_py
	 * @return  the value of j_org_info.org_short_name_py
	 * @mbg.generated
	 */
	public String getOrgShortNamePy() {
		return orgShortNamePy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.org_short_name_py
	 * @param orgShortNamePy  the value for j_org_info.org_short_name_py
	 * @mbg.generated
	 */
	public void setOrgShortNamePy(String orgShortNamePy) {
		this.orgShortNamePy = orgShortNamePy == null ? null : orgShortNamePy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.system_type_id
	 * @return  the value of j_org_info.system_type_id
	 * @mbg.generated
	 */
	public String getSystemTypeId() {
		return systemTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.system_type_id
	 * @param systemTypeId  the value for j_org_info.system_type_id
	 * @mbg.generated
	 */
	public void setSystemTypeId(String systemTypeId) {
		this.systemTypeId = systemTypeId == null ? null : systemTypeId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.org_level_id
	 * @return  the value of j_org_info.org_level_id
	 * @mbg.generated
	 */
	public String getOrgLevelId() {
		return orgLevelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.org_level_id
	 * @param orgLevelId  the value for j_org_info.org_level_id
	 * @mbg.generated
	 */
	public void setOrgLevelId(String orgLevelId) {
		this.orgLevelId = orgLevelId == null ? null : orgLevelId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.org_category_id
	 * @return  the value of j_org_info.org_category_id
	 * @mbg.generated
	 */
	public String getOrgCategoryId() {
		return orgCategoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.org_category_id
	 * @param orgCategoryId  the value for j_org_info.org_category_id
	 * @mbg.generated
	 */
	public void setOrgCategoryId(String orgCategoryId) {
		this.orgCategoryId = orgCategoryId == null ? null : orgCategoryId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.org_category_sub_id
	 * @return  the value of j_org_info.org_category_sub_id
	 * @mbg.generated
	 */
	public String getOrgCategorySubId() {
		return orgCategorySubId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.org_category_sub_id
	 * @param orgCategorySubId  the value for j_org_info.org_category_sub_id
	 * @mbg.generated
	 */
	public void setOrgCategorySubId(String orgCategorySubId) {
		this.orgCategorySubId = orgCategorySubId == null ? null : orgCategorySubId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.department_id
	 * @return  the value of j_org_info.department_id
	 * @mbg.generated
	 */
	public String getDepartmentId() {
		return departmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.department_id
	 * @param departmentId  the value for j_org_info.department_id
	 * @mbg.generated
	 */
	public void setDepartmentId(String departmentId) {
		this.departmentId = departmentId == null ? null : departmentId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.Industry_class_sub_id
	 * @return  the value of j_org_info.Industry_class_sub_id
	 * @mbg.generated
	 */
	public String getIndustryClassSubId() {
		return industryClassSubId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.Industry_class_sub_id
	 * @param industryClassSubId  the value for j_org_info.Industry_class_sub_id
	 * @mbg.generated
	 */
	public void setIndustryClassSubId(String industryClassSubId) {
		this.industryClassSubId = industryClassSubId == null ? null : industryClassSubId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.Industry_class_id
	 * @return  the value of j_org_info.Industry_class_id
	 * @mbg.generated
	 */
	public String getIndustryClassId() {
		return industryClassId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.Industry_class_id
	 * @param industryClassId  the value for j_org_info.Industry_class_id
	 * @mbg.generated
	 */
	public void setIndustryClassId(String industryClassId) {
		this.industryClassId = industryClassId == null ? null : industryClassId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.org_attr_id
	 * @return  the value of j_org_info.org_attr_id
	 * @mbg.generated
	 */
	public String getOrgAttrId() {
		return orgAttrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.org_attr_id
	 * @param orgAttrId  the value for j_org_info.org_attr_id
	 * @mbg.generated
	 */
	public void setOrgAttrId(String orgAttrId) {
		this.orgAttrId = orgAttrId == null ? null : orgAttrId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.org_sort_id
	 * @return  the value of j_org_info.org_sort_id
	 * @mbg.generated
	 */
	public String getOrgSortId() {
		return orgSortId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.org_sort_id
	 * @param orgSortId  the value for j_org_info.org_sort_id
	 * @mbg.generated
	 */
	public void setOrgSortId(String orgSortId) {
		this.orgSortId = orgSortId == null ? null : orgSortId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.org_sort_sub_id
	 * @return  the value of j_org_info.org_sort_sub_id
	 * @mbg.generated
	 */
	public String getOrgSortSubId() {
		return orgSortSubId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.org_sort_sub_id
	 * @param orgSortSubId  the value for j_org_info.org_sort_sub_id
	 * @mbg.generated
	 */
	public void setOrgSortSubId(String orgSortSubId) {
		this.orgSortSubId = orgSortSubId == null ? null : orgSortSubId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.outlay_shape_id
	 * @return  the value of j_org_info.outlay_shape_id
	 * @mbg.generated
	 */
	public String getOutlayShapeId() {
		return outlayShapeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.outlay_shape_id
	 * @param outlayShapeId  the value for j_org_info.outlay_shape_id
	 * @mbg.generated
	 */
	public void setOutlayShapeId(String outlayShapeId) {
		this.outlayShapeId = outlayShapeId == null ? null : outlayShapeId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.finance_budget_code
	 * @return  the value of j_org_info.finance_budget_code
	 * @mbg.generated
	 */
	public String getFinanceBudgetCode() {
		return financeBudgetCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.finance_budget_code
	 * @param financeBudgetCode  the value for j_org_info.finance_budget_code
	 * @mbg.generated
	 */
	public void setFinanceBudgetCode(String financeBudgetCode) {
		this.financeBudgetCode = financeBudgetCode == null ? null : financeBudgetCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.is_public
	 * @return  the value of j_org_info.is_public
	 * @mbg.generated
	 */
	public String getIsPublic() {
		return isPublic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.is_public
	 * @param isPublic  the value for j_org_info.is_public
	 * @mbg.generated
	 */
	public void setIsPublic(String isPublic) {
		this.isPublic = isPublic == null ? null : isPublic.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.is_development_area_org
	 * @return  the value of j_org_info.is_development_area_org
	 * @mbg.generated
	 */
	public String getIsDevelopmentAreaOrg() {
		return isDevelopmentAreaOrg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.is_development_area_org
	 * @param isDevelopmentAreaOrg  the value for j_org_info.is_development_area_org
	 * @mbg.generated
	 */
	public void setIsDevelopmentAreaOrg(String isDevelopmentAreaOrg) {
		this.isDevelopmentAreaOrg = isDevelopmentAreaOrg == null ? null : isDevelopmentAreaOrg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.cangong_piwen
	 * @return  the value of j_org_info.cangong_piwen
	 * @mbg.generated
	 */
	public String getCangongPiwen() {
		return cangongPiwen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.cangong_piwen
	 * @param cangongPiwen  the value for j_org_info.cangong_piwen
	 * @mbg.generated
	 */
	public void setCangongPiwen(String cangongPiwen) {
		this.cangongPiwen = cangongPiwen == null ? null : cangongPiwen.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.establishment_date
	 * @return  the value of j_org_info.establishment_date
	 * @mbg.generated
	 */
	public String getEstablishmentDate() {
		return establishmentDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.establishment_date
	 * @param establishmentDate  the value for j_org_info.establishment_date
	 * @mbg.generated
	 */
	public void setEstablishmentDate(String establishmentDate) {
		this.establishmentDate = establishmentDate == null ? null : establishmentDate.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.telphone
	 * @return  the value of j_org_info.telphone
	 * @mbg.generated
	 */
	public String getTelphone() {
		return telphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.telphone
	 * @param telphone  the value for j_org_info.telphone
	 * @mbg.generated
	 */
	public void setTelphone(String telphone) {
		this.telphone = telphone == null ? null : telphone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.post_code
	 * @return  the value of j_org_info.post_code
	 * @mbg.generated
	 */
	public String getPostCode() {
		return postCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.post_code
	 * @param postCode  the value for j_org_info.post_code
	 * @mbg.generated
	 */
	public void setPostCode(String postCode) {
		this.postCode = postCode == null ? null : postCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.domain_zh
	 * @return  the value of j_org_info.domain_zh
	 * @mbg.generated
	 */
	public String getDomainZh() {
		return domainZh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.domain_zh
	 * @param domainZh  the value for j_org_info.domain_zh
	 * @mbg.generated
	 */
	public void setDomainZh(String domainZh) {
		this.domainZh = domainZh == null ? null : domainZh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.domain_en
	 * @return  the value of j_org_info.domain_en
	 * @mbg.generated
	 */
	public String getDomainEn() {
		return domainEn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.domain_en
	 * @param domainEn  the value for j_org_info.domain_en
	 * @mbg.generated
	 */
	public void setDomainEn(String domainEn) {
		this.domainEn = domainEn == null ? null : domainEn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.address
	 * @return  the value of j_org_info.address
	 * @mbg.generated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.address
	 * @param address  the value for j_org_info.address
	 * @mbg.generated
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.remark
	 * @return  the value of j_org_info.remark
	 * @mbg.generated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.remark
	 * @param remark  the value for j_org_info.remark
	 * @mbg.generated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.org_code
	 * @return  the value of j_org_info.org_code
	 * @mbg.generated
	 */
	public String getOrgCode() {
		return orgCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.org_code
	 * @param orgCode  the value for j_org_info.org_code
	 * @mbg.generated
	 */
	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode == null ? null : orgCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.legal_person_certificate_no
	 * @return  the value of j_org_info.legal_person_certificate_no
	 * @mbg.generated
	 */
	public String getLegalPersonCertificateNo() {
		return legalPersonCertificateNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.legal_person_certificate_no
	 * @param legalPersonCertificateNo  the value for j_org_info.legal_person_certificate_no
	 * @mbg.generated
	 */
	public void setLegalPersonCertificateNo(String legalPersonCertificateNo) {
		this.legalPersonCertificateNo = legalPersonCertificateNo == null ? null : legalPersonCertificateNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.cangong_status
	 * @return  the value of j_org_info.cangong_status
	 * @mbg.generated
	 */
	public Short getCangongStatus() {
		return cangongStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.cangong_status
	 * @param cangongStatus  the value for j_org_info.cangong_status
	 * @mbg.generated
	 */
	public void setCangongStatus(Short cangongStatus) {
		this.cangongStatus = cangongStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.org_main_obligation_id
	 * @return  the value of j_org_info.org_main_obligation_id
	 * @mbg.generated
	 */
	public String getOrgMainObligationId() {
		return orgMainObligationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.org_main_obligation_id
	 * @param orgMainObligationId  the value for j_org_info.org_main_obligation_id
	 * @mbg.generated
	 */
	public void setOrgMainObligationId(String orgMainObligationId) {
		this.orgMainObligationId = orgMainObligationId == null ? null : orgMainObligationId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.inner_org_count
	 * @return  the value of j_org_info.inner_org_count
	 * @mbg.generated
	 */
	public Integer getInnerOrgCount() {
		return innerOrgCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.inner_org_count
	 * @param innerOrgCount  the value for j_org_info.inner_org_count
	 * @mbg.generated
	 */
	public void setInnerOrgCount(Integer innerOrgCount) {
		this.innerOrgCount = innerOrgCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.other_org_count
	 * @return  the value of j_org_info.other_org_count
	 * @mbg.generated
	 */
	public Integer getOtherOrgCount() {
		return otherOrgCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.other_org_count
	 * @param otherOrgCount  the value for j_org_info.other_org_count
	 * @mbg.generated
	 */
	public void setOtherOrgCount(Integer otherOrgCount) {
		this.otherOrgCount = otherOrgCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.xz_qebk_count
	 * @return  the value of j_org_info.xz_qebk_count
	 * @mbg.generated
	 */
	public Integer getXzQebkCount() {
		return xzQebkCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.xz_qebk_count
	 * @param xzQebkCount  the value for j_org_info.xz_qebk_count
	 * @mbg.generated
	 */
	public void setXzQebkCount(Integer xzQebkCount) {
		this.xzQebkCount = xzQebkCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.gq_cebt_count
	 * @return  the value of j_org_info.gq_cebt_count
	 * @mbg.generated
	 */
	public Integer getGqCebtCount() {
		return gqCebtCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.gq_cebt_count
	 * @param gqCebtCount  the value for j_org_info.gq_cebt_count
	 * @mbg.generated
	 */
	public void setGqCebtCount(Integer gqCebtCount) {
		this.gqCebtCount = gqCebtCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.other_zszz_count
	 * @return  the value of j_org_info.other_zszz_count
	 * @mbg.generated
	 */
	public Integer getOtherZszzCount() {
		return otherZszzCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.other_zszz_count
	 * @param otherZszzCount  the value for j_org_info.other_zszz_count
	 * @mbg.generated
	 */
	public void setOtherZszzCount(Integer otherZszzCount) {
		this.otherZszzCount = otherZszzCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.dept_leader_count
	 * @return  the value of j_org_info.dept_leader_count
	 * @mbg.generated
	 */
	public Integer getDeptLeaderCount() {
		return deptLeaderCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.dept_leader_count
	 * @param deptLeaderCount  the value for j_org_info.dept_leader_count
	 * @mbg.generated
	 */
	public void setDeptLeaderCount(Integer deptLeaderCount) {
		this.deptLeaderCount = deptLeaderCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.dept_leader_high_count
	 * @return  the value of j_org_info.dept_leader_high_count
	 * @mbg.generated
	 */
	public Integer getDeptLeaderHighCount() {
		return deptLeaderHighCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.dept_leader_high_count
	 * @param deptLeaderHighCount  the value for j_org_info.dept_leader_high_count
	 * @mbg.generated
	 */
	public void setDeptLeaderHighCount(Integer deptLeaderHighCount) {
		this.deptLeaderHighCount = deptLeaderHighCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.dept_vice_lead_count
	 * @return  the value of j_org_info.dept_vice_lead_count
	 * @mbg.generated
	 */
	public Integer getDeptViceLeadCount() {
		return deptViceLeadCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.dept_vice_lead_count
	 * @param deptViceLeadCount  the value for j_org_info.dept_vice_lead_count
	 * @mbg.generated
	 */
	public void setDeptViceLeadCount(Integer deptViceLeadCount) {
		this.deptViceLeadCount = deptViceLeadCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.dept_vice_lead_high_count
	 * @return  the value of j_org_info.dept_vice_lead_high_count
	 * @mbg.generated
	 */
	public Integer getDeptViceLeadHighCount() {
		return deptViceLeadHighCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.dept_vice_lead_high_count
	 * @param deptViceLeadHighCount  the value for j_org_info.dept_vice_lead_high_count
	 * @mbg.generated
	 */
	public void setDeptViceLeadHighCount(Integer deptViceLeadHighCount) {
		this.deptViceLeadHighCount = deptViceLeadHighCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.inspect_discipline_count
	 * @return  the value of j_org_info.inspect_discipline_count
	 * @mbg.generated
	 */
	public Integer getInspectDisciplineCount() {
		return inspectDisciplineCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.inspect_discipline_count
	 * @param inspectDisciplineCount  the value for j_org_info.inspect_discipline_count
	 * @mbg.generated
	 */
	public void setInspectDisciplineCount(Integer inspectDisciplineCount) {
		this.inspectDisciplineCount = inspectDisciplineCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.other_count
	 * @return  the value of j_org_info.other_count
	 * @mbg.generated
	 */
	public Integer getOtherCount() {
		return otherCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.other_count
	 * @param otherCount  the value for j_org_info.other_count
	 * @mbg.generated
	 */
	public void setOtherCount(Integer otherCount) {
		this.otherCount = otherCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.inner_leader_count
	 * @return  the value of j_org_info.inner_leader_count
	 * @mbg.generated
	 */
	public Integer getInnerLeaderCount() {
		return innerLeaderCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.inner_leader_count
	 * @param innerLeaderCount  the value for j_org_info.inner_leader_count
	 * @mbg.generated
	 */
	public void setInnerLeaderCount(Integer innerLeaderCount) {
		this.innerLeaderCount = innerLeaderCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.inner_leader_high_count
	 * @return  the value of j_org_info.inner_leader_high_count
	 * @mbg.generated
	 */
	public Integer getInnerLeaderHighCount() {
		return innerLeaderHighCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.inner_leader_high_count
	 * @param innerLeaderHighCount  the value for j_org_info.inner_leader_high_count
	 * @mbg.generated
	 */
	public void setInnerLeaderHighCount(Integer innerLeaderHighCount) {
		this.innerLeaderHighCount = innerLeaderHighCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.inner_vice_lead_count
	 * @return  the value of j_org_info.inner_vice_lead_count
	 * @mbg.generated
	 */
	public Integer getInnerViceLeadCount() {
		return innerViceLeadCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.inner_vice_lead_count
	 * @param innerViceLeadCount  the value for j_org_info.inner_vice_lead_count
	 * @mbg.generated
	 */
	public void setInnerViceLeadCount(Integer innerViceLeadCount) {
		this.innerViceLeadCount = innerViceLeadCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.inner_vice_lead_high_count
	 * @return  the value of j_org_info.inner_vice_lead_high_count
	 * @mbg.generated
	 */
	public Integer getInnerViceLeadHighCount() {
		return innerViceLeadHighCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.inner_vice_lead_high_count
	 * @param innerViceLeadHighCount  the value for j_org_info.inner_vice_lead_high_count
	 * @mbg.generated
	 */
	public void setInnerViceLeadHighCount(Integer innerViceLeadHighCount) {
		this.innerViceLeadHighCount = innerViceLeadHighCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.dept_not_leader_count
	 * @return  the value of j_org_info.dept_not_leader_count
	 * @mbg.generated
	 */
	public Integer getDeptNotLeaderCount() {
		return deptNotLeaderCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.dept_not_leader_count
	 * @param deptNotLeaderCount  the value for j_org_info.dept_not_leader_count
	 * @mbg.generated
	 */
	public void setDeptNotLeaderCount(Integer deptNotLeaderCount) {
		this.deptNotLeaderCount = deptNotLeaderCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.dept_not_vice_lead_count
	 * @return  the value of j_org_info.dept_not_vice_lead_count
	 * @mbg.generated
	 */
	public Integer getDeptNotViceLeadCount() {
		return deptNotViceLeadCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.dept_not_vice_lead_count
	 * @param deptNotViceLeadCount  the value for j_org_info.dept_not_vice_lead_count
	 * @mbg.generated
	 */
	public void setDeptNotViceLeadCount(Integer deptNotViceLeadCount) {
		this.deptNotViceLeadCount = deptNotViceLeadCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.inner_not_lead_count
	 * @return  the value of j_org_info.inner_not_lead_count
	 * @mbg.generated
	 */
	public Integer getInnerNotLeadCount() {
		return innerNotLeadCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.inner_not_lead_count
	 * @param innerNotLeadCount  the value for j_org_info.inner_not_lead_count
	 * @mbg.generated
	 */
	public void setInnerNotLeadCount(Integer innerNotLeadCount) {
		this.innerNotLeadCount = innerNotLeadCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.inner_not_vice_lead_count
	 * @return  the value of j_org_info.inner_not_vice_lead_count
	 * @mbg.generated
	 */
	public Integer getInnerNotViceLeadCount() {
		return innerNotViceLeadCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.inner_not_vice_lead_count
	 * @param innerNotViceLeadCount  the value for j_org_info.inner_not_vice_lead_count
	 * @mbg.generated
	 */
	public void setInnerNotViceLeadCount(Integer innerNotViceLeadCount) {
		this.innerNotViceLeadCount = innerNotViceLeadCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.manager_count
	 * @return  the value of j_org_info.manager_count
	 * @mbg.generated
	 */
	public Integer getManagerCount() {
		return managerCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.manager_count
	 * @param managerCount  the value for j_org_info.manager_count
	 * @mbg.generated
	 */
	public void setManagerCount(Integer managerCount) {
		this.managerCount = managerCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.professional_skill_count
	 * @return  the value of j_org_info.professional_skill_count
	 * @mbg.generated
	 */
	public Integer getProfessionalSkillCount() {
		return professionalSkillCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.professional_skill_count
	 * @param professionalSkillCount  the value for j_org_info.professional_skill_count
	 * @mbg.generated
	 */
	public void setProfessionalSkillCount(Integer professionalSkillCount) {
		this.professionalSkillCount = professionalSkillCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.gongqing_skill_count
	 * @return  the value of j_org_info.gongqing_skill_count
	 * @mbg.generated
	 */
	public Integer getGongqingSkillCount() {
		return gongqingSkillCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.gongqing_skill_count
	 * @param gongqingSkillCount  the value for j_org_info.gongqing_skill_count
	 * @mbg.generated
	 */
	public void setGongqingSkillCount(Integer gongqingSkillCount) {
		this.gongqingSkillCount = gongqingSkillCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.special_count
	 * @return  the value of j_org_info.special_count
	 * @mbg.generated
	 */
	public Integer getSpecialCount() {
		return specialCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.special_count
	 * @param specialCount  the value for j_org_info.special_count
	 * @mbg.generated
	 */
	public void setSpecialCount(Integer specialCount) {
		this.specialCount = specialCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.piwen_id
	 * @return  the value of j_org_info.piwen_id
	 * @mbg.generated
	 */
	public String getPiwenId() {
		return piwenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.piwen_id
	 * @param piwenId  the value for j_org_info.piwen_id
	 * @mbg.generated
	 */
	public void setPiwenId(String piwenId) {
		this.piwenId = piwenId == null ? null : piwenId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.pw_code
	 * @return  the value of j_org_info.pw_code
	 * @mbg.generated
	 */
	public String getPwCode() {
		return pwCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.pw_code
	 * @param pwCode  the value for j_org_info.pw_code
	 * @mbg.generated
	 */
	public void setPwCode(String pwCode) {
		this.pwCode = pwCode == null ? null : pwCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.status
	 * @return  the value of j_org_info.status
	 * @mbg.generated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.status
	 * @param status  the value for j_org_info.status
	 * @mbg.generated
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.createtime
	 * @return  the value of j_org_info.createtime
	 * @mbg.generated
	 */
	public String getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.createtime
	 * @param createtime  the value for j_org_info.createtime
	 * @mbg.generated
	 */
	public void setCreatetime(String createtime) {
		this.createtime = createtime == null ? null : createtime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.SBJFZ
	 * @return  the value of j_org_info.SBJFZ
	 * @mbg.generated
	 */
	public Integer getSbjfz() {
		return sbjfz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.SBJFZ
	 * @param sbjfz  the value for j_org_info.SBJFZ
	 * @mbg.generated
	 */
	public void setSbjfz(Integer sbjfz) {
		this.sbjfz = sbjfz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.TJJZZ
	 * @return  the value of j_org_info.TJJZZ
	 * @mbg.generated
	 */
	public Integer getTjjzz() {
		return tjjzz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.TJJZZ
	 * @param tjjzz  the value for j_org_info.TJJZZ
	 * @mbg.generated
	 */
	public void setTjjzz(Integer tjjzz) {
		this.tjjzz = tjjzz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.TJJFZ
	 * @return  the value of j_org_info.TJJFZ
	 * @mbg.generated
	 */
	public Integer getTjjfz() {
		return tjjfz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.TJJFZ
	 * @param tjjfz  the value for j_org_info.TJJFZ
	 * @mbg.generated
	 */
	public void setTjjfz(Integer tjjfz) {
		this.tjjfz = tjjfz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.XCJZZ
	 * @return  the value of j_org_info.XCJZZ
	 * @mbg.generated
	 */
	public Integer getXcjzz() {
		return xcjzz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.XCJZZ
	 * @param xcjzz  the value for j_org_info.XCJZZ
	 * @mbg.generated
	 */
	public void setXcjzz(Integer xcjzz) {
		this.xcjzz = xcjzz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.XCJFZ
	 * @return  the value of j_org_info.XCJFZ
	 * @mbg.generated
	 */
	public Integer getXcjfz() {
		return xcjfz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.XCJFZ
	 * @param xcjfz  the value for j_org_info.XCJFZ
	 * @mbg.generated
	 */
	public void setXcjfz(Integer xcjfz) {
		this.xcjfz = xcjfz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.XKJZZ
	 * @return  the value of j_org_info.XKJZZ
	 * @mbg.generated
	 */
	public Integer getXkjzz() {
		return xkjzz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.XKJZZ
	 * @param xkjzz  the value for j_org_info.XKJZZ
	 * @mbg.generated
	 */
	public void setXkjzz(Integer xkjzz) {
		this.xkjzz = xkjzz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.XKJFZ
	 * @return  the value of j_org_info.XKJFZ
	 * @mbg.generated
	 */
	public Integer getXkjfz() {
		return xkjfz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.XKJFZ
	 * @param xkjfz  the value for j_org_info.XKJFZ
	 * @mbg.generated
	 */
	public void setXkjfz(Integer xkjfz) {
		this.xkjfz = xkjfz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.GJZZ
	 * @return  the value of j_org_info.GJZZ
	 * @mbg.generated
	 */
	public Integer getGjzz() {
		return gjzz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.GJZZ
	 * @param gjzz  the value for j_org_info.GJZZ
	 * @mbg.generated
	 */
	public void setGjzz(Integer gjzz) {
		this.gjzz = gjzz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.GJFZ
	 * @return  the value of j_org_info.GJFZ
	 * @mbg.generated
	 */
	public Integer getGjfz() {
		return gjfz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.GJFZ
	 * @param gjfz  the value for j_org_info.GJFZ
	 * @mbg.generated
	 */
	public void setGjfz(Integer gjfz) {
		this.gjfz = gjfz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.WDJ
	 * @return  the value of j_org_info.WDJ
	 * @mbg.generated
	 */
	public Integer getWdj() {
		return wdj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.WDJ
	 * @param wdj  the value for j_org_info.WDJ
	 * @mbg.generated
	 */
	public void setWdj(Integer wdj) {
		this.wdj = wdj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.QT
	 * @return  the value of j_org_info.QT
	 * @mbg.generated
	 */
	public Integer getQt() {
		return qt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.QT
	 * @param qt  the value for j_org_info.QT
	 * @mbg.generated
	 */
	public void setQt(Integer qt) {
		this.qt = qt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.XSY
	 * @return  the value of j_org_info.XSY
	 * @mbg.generated
	 */
	public Integer getXsy() {
		return xsy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.XSY
	 * @param xsy  the value for j_org_info.XSY
	 * @mbg.generated
	 */
	public void setXsy(Integer xsy) {
		this.xsy = xsy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.FXSY
	 * @return  the value of j_org_info.FXSY
	 * @mbg.generated
	 */
	public Integer getFxsy() {
		return fxsy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.FXSY
	 * @param fxsy  the value for j_org_info.FXSY
	 * @mbg.generated
	 */
	public void setFxsy(Integer fxsy) {
		this.fxsy = fxsy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.DYY
	 * @return  the value of j_org_info.DYY
	 * @mbg.generated
	 */
	public Integer getDyy() {
		return dyy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.DYY
	 * @param dyy  the value for j_org_info.DYY
	 * @mbg.generated
	 */
	public void setDyy(Integer dyy) {
		this.dyy = dyy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.FDYY
	 * @return  the value of j_org_info.FDYY
	 * @mbg.generated
	 */
	public Integer getFdyy() {
		return fdyy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.FDYY
	 * @param fdyy  the value for j_org_info.FDYY
	 * @mbg.generated
	 */
	public void setFdyy(Integer fdyy) {
		this.fdyy = fdyy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.ZRKY
	 * @return  the value of j_org_info.ZRKY
	 * @mbg.generated
	 */
	public Integer getZrky() {
		return zrky;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.ZRKY
	 * @param zrky  the value for j_org_info.ZRKY
	 * @mbg.generated
	 */
	public void setZrky(Integer zrky) {
		this.zrky = zrky;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.FZRKY
	 * @return  the value of j_org_info.FZRKY
	 * @mbg.generated
	 */
	public Integer getFzrky() {
		return fzrky;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.FZRKY
	 * @param fzrky  the value for j_org_info.FZRKY
	 * @mbg.generated
	 */
	public void setFzrky(Integer fzrky) {
		this.fzrky = fzrky;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column j_org_info.approval_status
	 * @return  the value of j_org_info.approval_status
	 * @mbg.generated
	 */
	public String getApprovalStatus() {
		return approvalStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column j_org_info.approval_status
	 * @param approvalStatus  the value for j_org_info.approval_status
	 * @mbg.generated
	 */
	public void setApprovalStatus(String approvalStatus) {
		this.approvalStatus = approvalStatus == null ? null : approvalStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table j_org_info
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		JOrgInfo other = (JOrgInfo) that;
		return (this.getOrgId() == null ? other.getOrgId() == null : this.getOrgId().equals(other.getOrgId()))
				&& (this.getOrgType() == null ? other.getOrgType() == null
						: this.getOrgType().equals(other.getOrgType()))
				&& (this.getAreaCode() == null ? other.getAreaCode() == null
						: this.getAreaCode().equals(other.getAreaCode()))
				&& (this.getParentOrgId() == null ? other.getParentOrgId() == null
						: this.getParentOrgId().equals(other.getParentOrgId()))
				&& (this.getSortSerialNo() == null ? other.getSortSerialNo() == null
						: this.getSortSerialNo().equals(other.getSortSerialNo()))
				&& (this.getOrgEncode() == null ? other.getOrgEncode() == null
						: this.getOrgEncode().equals(other.getOrgEncode()))
				&& (this.getOrgName() == null ? other.getOrgName() == null
						: this.getOrgName().equals(other.getOrgName()))
				&& (this.getOrgNamePy() == null ? other.getOrgNamePy() == null
						: this.getOrgNamePy().equals(other.getOrgNamePy()))
				&& (this.getOtherName() == null ? other.getOtherName() == null
						: this.getOtherName().equals(other.getOtherName()))
				&& (this.getOtherNamePy() == null ? other.getOtherNamePy() == null
						: this.getOtherNamePy().equals(other.getOtherNamePy()))
				&& (this.getOrgShortName() == null ? other.getOrgShortName() == null
						: this.getOrgShortName().equals(other.getOrgShortName()))
				&& (this.getOrgPropertyId() == null ? other.getOrgPropertyId() == null
						: this.getOrgPropertyId().equals(other.getOrgPropertyId()))
				&& (this.getOrgShortNamePy() == null ? other.getOrgShortNamePy() == null
						: this.getOrgShortNamePy().equals(other.getOrgShortNamePy()))
				&& (this.getSystemTypeId() == null ? other.getSystemTypeId() == null
						: this.getSystemTypeId().equals(other.getSystemTypeId()))
				&& (this.getOrgLevelId() == null ? other.getOrgLevelId() == null
						: this.getOrgLevelId().equals(other.getOrgLevelId()))
				&& (this.getOrgCategoryId() == null ? other.getOrgCategoryId() == null
						: this.getOrgCategoryId().equals(other.getOrgCategoryId()))
				&& (this.getOrgCategorySubId() == null ? other.getOrgCategorySubId() == null
						: this.getOrgCategorySubId().equals(other.getOrgCategorySubId()))
				&& (this.getDepartmentId() == null ? other.getDepartmentId() == null
						: this.getDepartmentId().equals(other.getDepartmentId()))
				&& (this.getIndustryClassSubId() == null ? other.getIndustryClassSubId() == null
						: this.getIndustryClassSubId().equals(other.getIndustryClassSubId()))
				&& (this.getIndustryClassId() == null ? other.getIndustryClassId() == null
						: this.getIndustryClassId().equals(other.getIndustryClassId()))
				&& (this.getOrgAttrId() == null ? other.getOrgAttrId() == null
						: this.getOrgAttrId().equals(other.getOrgAttrId()))
				&& (this.getOrgSortId() == null ? other.getOrgSortId() == null
						: this.getOrgSortId().equals(other.getOrgSortId()))
				&& (this.getOrgSortSubId() == null ? other.getOrgSortSubId() == null
						: this.getOrgSortSubId().equals(other.getOrgSortSubId()))
				&& (this.getOutlayShapeId() == null ? other.getOutlayShapeId() == null
						: this.getOutlayShapeId().equals(other.getOutlayShapeId()))
				&& (this.getFinanceBudgetCode() == null ? other.getFinanceBudgetCode() == null
						: this.getFinanceBudgetCode().equals(other.getFinanceBudgetCode()))
				&& (this.getIsPublic() == null ? other.getIsPublic() == null
						: this.getIsPublic().equals(other.getIsPublic()))
				&& (this.getIsDevelopmentAreaOrg() == null ? other.getIsDevelopmentAreaOrg() == null
						: this.getIsDevelopmentAreaOrg().equals(other.getIsDevelopmentAreaOrg()))
				&& (this.getCangongPiwen() == null ? other.getCangongPiwen() == null
						: this.getCangongPiwen().equals(other.getCangongPiwen()))
				&& (this.getEstablishmentDate() == null ? other.getEstablishmentDate() == null
						: this.getEstablishmentDate().equals(other.getEstablishmentDate()))
				&& (this.getTelphone() == null ? other.getTelphone() == null
						: this.getTelphone().equals(other.getTelphone()))
				&& (this.getPostCode() == null ? other.getPostCode() == null
						: this.getPostCode().equals(other.getPostCode()))
				&& (this.getDomainZh() == null ? other.getDomainZh() == null
						: this.getDomainZh().equals(other.getDomainZh()))
				&& (this.getDomainEn() == null ? other.getDomainEn() == null
						: this.getDomainEn().equals(other.getDomainEn()))
				&& (this.getAddress() == null ? other.getAddress() == null
						: this.getAddress().equals(other.getAddress()))
				&& (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
				&& (this.getOrgCode() == null ? other.getOrgCode() == null
						: this.getOrgCode().equals(other.getOrgCode()))
				&& (this.getLegalPersonCertificateNo() == null ? other.getLegalPersonCertificateNo() == null
						: this.getLegalPersonCertificateNo().equals(other.getLegalPersonCertificateNo()))
				&& (this.getCangongStatus() == null ? other.getCangongStatus() == null
						: this.getCangongStatus().equals(other.getCangongStatus()))
				&& (this.getOrgMainObligationId() == null ? other.getOrgMainObligationId() == null
						: this.getOrgMainObligationId().equals(other.getOrgMainObligationId()))
				&& (this.getInnerOrgCount() == null ? other.getInnerOrgCount() == null
						: this.getInnerOrgCount().equals(other.getInnerOrgCount()))
				&& (this.getOtherOrgCount() == null ? other.getOtherOrgCount() == null
						: this.getOtherOrgCount().equals(other.getOtherOrgCount()))
				&& (this.getXzQebkCount() == null ? other.getXzQebkCount() == null
						: this.getXzQebkCount().equals(other.getXzQebkCount()))
				&& (this.getGqCebtCount() == null ? other.getGqCebtCount() == null
						: this.getGqCebtCount().equals(other.getGqCebtCount()))
				&& (this.getOtherZszzCount() == null ? other.getOtherZszzCount() == null
						: this.getOtherZszzCount().equals(other.getOtherZszzCount()))
				&& (this.getDeptLeaderCount() == null ? other.getDeptLeaderCount() == null
						: this.getDeptLeaderCount().equals(other.getDeptLeaderCount()))
				&& (this.getDeptLeaderHighCount() == null ? other.getDeptLeaderHighCount() == null
						: this.getDeptLeaderHighCount().equals(other.getDeptLeaderHighCount()))
				&& (this.getDeptViceLeadCount() == null ? other.getDeptViceLeadCount() == null
						: this.getDeptViceLeadCount().equals(other.getDeptViceLeadCount()))
				&& (this.getDeptViceLeadHighCount() == null ? other.getDeptViceLeadHighCount() == null
						: this.getDeptViceLeadHighCount().equals(other.getDeptViceLeadHighCount()))
				&& (this.getInspectDisciplineCount() == null ? other.getInspectDisciplineCount() == null
						: this.getInspectDisciplineCount().equals(other.getInspectDisciplineCount()))
				&& (this.getOtherCount() == null ? other.getOtherCount() == null
						: this.getOtherCount().equals(other.getOtherCount()))
				&& (this.getInnerLeaderCount() == null ? other.getInnerLeaderCount() == null
						: this.getInnerLeaderCount().equals(other.getInnerLeaderCount()))
				&& (this.getInnerLeaderHighCount() == null ? other.getInnerLeaderHighCount() == null
						: this.getInnerLeaderHighCount().equals(other.getInnerLeaderHighCount()))
				&& (this.getInnerViceLeadCount() == null ? other.getInnerViceLeadCount() == null
						: this.getInnerViceLeadCount().equals(other.getInnerViceLeadCount()))
				&& (this.getInnerViceLeadHighCount() == null ? other.getInnerViceLeadHighCount() == null
						: this.getInnerViceLeadHighCount().equals(other.getInnerViceLeadHighCount()))
				&& (this.getDeptNotLeaderCount() == null ? other.getDeptNotLeaderCount() == null
						: this.getDeptNotLeaderCount().equals(other.getDeptNotLeaderCount()))
				&& (this.getDeptNotViceLeadCount() == null ? other.getDeptNotViceLeadCount() == null
						: this.getDeptNotViceLeadCount().equals(other.getDeptNotViceLeadCount()))
				&& (this.getInnerNotLeadCount() == null ? other.getInnerNotLeadCount() == null
						: this.getInnerNotLeadCount().equals(other.getInnerNotLeadCount()))
				&& (this.getInnerNotViceLeadCount() == null ? other.getInnerNotViceLeadCount() == null
						: this.getInnerNotViceLeadCount().equals(other.getInnerNotViceLeadCount()))
				&& (this.getManagerCount() == null ? other.getManagerCount() == null
						: this.getManagerCount().equals(other.getManagerCount()))
				&& (this.getProfessionalSkillCount() == null ? other.getProfessionalSkillCount() == null
						: this.getProfessionalSkillCount().equals(other.getProfessionalSkillCount()))
				&& (this.getGongqingSkillCount() == null ? other.getGongqingSkillCount() == null
						: this.getGongqingSkillCount().equals(other.getGongqingSkillCount()))
				&& (this.getSpecialCount() == null ? other.getSpecialCount() == null
						: this.getSpecialCount().equals(other.getSpecialCount()))
				&& (this.getPiwenId() == null ? other.getPiwenId() == null
						: this.getPiwenId().equals(other.getPiwenId()))
				&& (this.getPwCode() == null ? other.getPwCode() == null : this.getPwCode().equals(other.getPwCode()))
				&& (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
				&& (this.getCreater() == null ? other.getCreater() == null
						: this.getCreater().equals(other.getCreater()))
				&& (this.getCreatetime() == null ? other.getCreatetime() == null
						: this.getCreatetime().equals(other.getCreatetime()))
				&& (this.getUpdater() == null ? other.getUpdater() == null
						: this.getUpdater().equals(other.getUpdater()))
				&& (this.getSbjfz() == null ? other.getSbjfz() == null : this.getSbjfz().equals(other.getSbjfz()))
				&& (this.getTjjzz() == null ? other.getTjjzz() == null : this.getTjjzz().equals(other.getTjjzz()))
				&& (this.getTjjfz() == null ? other.getTjjfz() == null : this.getTjjfz().equals(other.getTjjfz()))
				&& (this.getXcjzz() == null ? other.getXcjzz() == null : this.getXcjzz().equals(other.getXcjzz()))
				&& (this.getXcjfz() == null ? other.getXcjfz() == null : this.getXcjfz().equals(other.getXcjfz()))
				&& (this.getXkjzz() == null ? other.getXkjzz() == null : this.getXkjzz().equals(other.getXkjzz()))
				&& (this.getXkjfz() == null ? other.getXkjfz() == null : this.getXkjfz().equals(other.getXkjfz()))
				&& (this.getGjzz() == null ? other.getGjzz() == null : this.getGjzz().equals(other.getGjzz()))
				&& (this.getGjfz() == null ? other.getGjfz() == null : this.getGjfz().equals(other.getGjfz()))
				&& (this.getWdj() == null ? other.getWdj() == null : this.getWdj().equals(other.getWdj()))
				&& (this.getQt() == null ? other.getQt() == null : this.getQt().equals(other.getQt()))
				&& (this.getXsy() == null ? other.getXsy() == null : this.getXsy().equals(other.getXsy()))
				&& (this.getFxsy() == null ? other.getFxsy() == null : this.getFxsy().equals(other.getFxsy()))
				&& (this.getDyy() == null ? other.getDyy() == null : this.getDyy().equals(other.getDyy()))
				&& (this.getFdyy() == null ? other.getFdyy() == null : this.getFdyy().equals(other.getFdyy()))
				&& (this.getZrky() == null ? other.getZrky() == null : this.getZrky().equals(other.getZrky()))
				&& (this.getFzrky() == null ? other.getFzrky() == null : this.getFzrky().equals(other.getFzrky()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null
						: this.getUpdateTime().equals(other.getUpdateTime()))
				&& (this.getApprovalStatus() == null ? other.getApprovalStatus() == null
						: this.getApprovalStatus().equals(other.getApprovalStatus()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table j_org_info
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getOrgId() == null) ? 0 : getOrgId().hashCode());
		result = prime * result + ((getOrgType() == null) ? 0 : getOrgType().hashCode());
		result = prime * result + ((getAreaCode() == null) ? 0 : getAreaCode().hashCode());
		result = prime * result + ((getParentOrgId() == null) ? 0 : getParentOrgId().hashCode());
		result = prime * result + ((getSortSerialNo() == null) ? 0 : getSortSerialNo().hashCode());
		result = prime * result + ((getOrgEncode() == null) ? 0 : getOrgEncode().hashCode());
		result = prime * result + ((getOrgName() == null) ? 0 : getOrgName().hashCode());
		result = prime * result + ((getOrgNamePy() == null) ? 0 : getOrgNamePy().hashCode());
		result = prime * result + ((getOtherName() == null) ? 0 : getOtherName().hashCode());
		result = prime * result + ((getOtherNamePy() == null) ? 0 : getOtherNamePy().hashCode());
		result = prime * result + ((getOrgShortName() == null) ? 0 : getOrgShortName().hashCode());
		result = prime * result + ((getOrgPropertyId() == null) ? 0 : getOrgPropertyId().hashCode());
		result = prime * result + ((getOrgShortNamePy() == null) ? 0 : getOrgShortNamePy().hashCode());
		result = prime * result + ((getSystemTypeId() == null) ? 0 : getSystemTypeId().hashCode());
		result = prime * result + ((getOrgLevelId() == null) ? 0 : getOrgLevelId().hashCode());
		result = prime * result + ((getOrgCategoryId() == null) ? 0 : getOrgCategoryId().hashCode());
		result = prime * result + ((getOrgCategorySubId() == null) ? 0 : getOrgCategorySubId().hashCode());
		result = prime * result + ((getDepartmentId() == null) ? 0 : getDepartmentId().hashCode());
		result = prime * result + ((getIndustryClassSubId() == null) ? 0 : getIndustryClassSubId().hashCode());
		result = prime * result + ((getIndustryClassId() == null) ? 0 : getIndustryClassId().hashCode());
		result = prime * result + ((getOrgAttrId() == null) ? 0 : getOrgAttrId().hashCode());
		result = prime * result + ((getOrgSortId() == null) ? 0 : getOrgSortId().hashCode());
		result = prime * result + ((getOrgSortSubId() == null) ? 0 : getOrgSortSubId().hashCode());
		result = prime * result + ((getOutlayShapeId() == null) ? 0 : getOutlayShapeId().hashCode());
		result = prime * result + ((getFinanceBudgetCode() == null) ? 0 : getFinanceBudgetCode().hashCode());
		result = prime * result + ((getIsPublic() == null) ? 0 : getIsPublic().hashCode());
		result = prime * result + ((getIsDevelopmentAreaOrg() == null) ? 0 : getIsDevelopmentAreaOrg().hashCode());
		result = prime * result + ((getCangongPiwen() == null) ? 0 : getCangongPiwen().hashCode());
		result = prime * result + ((getEstablishmentDate() == null) ? 0 : getEstablishmentDate().hashCode());
		result = prime * result + ((getTelphone() == null) ? 0 : getTelphone().hashCode());
		result = prime * result + ((getPostCode() == null) ? 0 : getPostCode().hashCode());
		result = prime * result + ((getDomainZh() == null) ? 0 : getDomainZh().hashCode());
		result = prime * result + ((getDomainEn() == null) ? 0 : getDomainEn().hashCode());
		result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
		result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
		result = prime * result + ((getOrgCode() == null) ? 0 : getOrgCode().hashCode());
		result = prime * result
				+ ((getLegalPersonCertificateNo() == null) ? 0 : getLegalPersonCertificateNo().hashCode());
		result = prime * result + ((getCangongStatus() == null) ? 0 : getCangongStatus().hashCode());
		result = prime * result + ((getOrgMainObligationId() == null) ? 0 : getOrgMainObligationId().hashCode());
		result = prime * result + ((getInnerOrgCount() == null) ? 0 : getInnerOrgCount().hashCode());
		result = prime * result + ((getOtherOrgCount() == null) ? 0 : getOtherOrgCount().hashCode());
		result = prime * result + ((getXzQebkCount() == null) ? 0 : getXzQebkCount().hashCode());
		result = prime * result + ((getGqCebtCount() == null) ? 0 : getGqCebtCount().hashCode());
		result = prime * result + ((getOtherZszzCount() == null) ? 0 : getOtherZszzCount().hashCode());
		result = prime * result + ((getDeptLeaderCount() == null) ? 0 : getDeptLeaderCount().hashCode());
		result = prime * result + ((getDeptLeaderHighCount() == null) ? 0 : getDeptLeaderHighCount().hashCode());
		result = prime * result + ((getDeptViceLeadCount() == null) ? 0 : getDeptViceLeadCount().hashCode());
		result = prime * result + ((getDeptViceLeadHighCount() == null) ? 0 : getDeptViceLeadHighCount().hashCode());
		result = prime * result + ((getInspectDisciplineCount() == null) ? 0 : getInspectDisciplineCount().hashCode());
		result = prime * result + ((getOtherCount() == null) ? 0 : getOtherCount().hashCode());
		result = prime * result + ((getInnerLeaderCount() == null) ? 0 : getInnerLeaderCount().hashCode());
		result = prime * result + ((getInnerLeaderHighCount() == null) ? 0 : getInnerLeaderHighCount().hashCode());
		result = prime * result + ((getInnerViceLeadCount() == null) ? 0 : getInnerViceLeadCount().hashCode());
		result = prime * result + ((getInnerViceLeadHighCount() == null) ? 0 : getInnerViceLeadHighCount().hashCode());
		result = prime * result + ((getDeptNotLeaderCount() == null) ? 0 : getDeptNotLeaderCount().hashCode());
		result = prime * result + ((getDeptNotViceLeadCount() == null) ? 0 : getDeptNotViceLeadCount().hashCode());
		result = prime * result + ((getInnerNotLeadCount() == null) ? 0 : getInnerNotLeadCount().hashCode());
		result = prime * result + ((getInnerNotViceLeadCount() == null) ? 0 : getInnerNotViceLeadCount().hashCode());
		result = prime * result + ((getManagerCount() == null) ? 0 : getManagerCount().hashCode());
		result = prime * result + ((getProfessionalSkillCount() == null) ? 0 : getProfessionalSkillCount().hashCode());
		result = prime * result + ((getGongqingSkillCount() == null) ? 0 : getGongqingSkillCount().hashCode());
		result = prime * result + ((getSpecialCount() == null) ? 0 : getSpecialCount().hashCode());
		result = prime * result + ((getPiwenId() == null) ? 0 : getPiwenId().hashCode());
		result = prime * result + ((getPwCode() == null) ? 0 : getPwCode().hashCode());
		result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
		result = prime * result + ((getCreater() == null) ? 0 : getCreater().hashCode());
		result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
		result = prime * result + ((getUpdater() == null) ? 0 : getUpdater().hashCode());
		result = prime * result + ((getSbjfz() == null) ? 0 : getSbjfz().hashCode());
		result = prime * result + ((getTjjzz() == null) ? 0 : getTjjzz().hashCode());
		result = prime * result + ((getTjjfz() == null) ? 0 : getTjjfz().hashCode());
		result = prime * result + ((getXcjzz() == null) ? 0 : getXcjzz().hashCode());
		result = prime * result + ((getXcjfz() == null) ? 0 : getXcjfz().hashCode());
		result = prime * result + ((getXkjzz() == null) ? 0 : getXkjzz().hashCode());
		result = prime * result + ((getXkjfz() == null) ? 0 : getXkjfz().hashCode());
		result = prime * result + ((getGjzz() == null) ? 0 : getGjzz().hashCode());
		result = prime * result + ((getGjfz() == null) ? 0 : getGjfz().hashCode());
		result = prime * result + ((getWdj() == null) ? 0 : getWdj().hashCode());
		result = prime * result + ((getQt() == null) ? 0 : getQt().hashCode());
		result = prime * result + ((getXsy() == null) ? 0 : getXsy().hashCode());
		result = prime * result + ((getFxsy() == null) ? 0 : getFxsy().hashCode());
		result = prime * result + ((getDyy() == null) ? 0 : getDyy().hashCode());
		result = prime * result + ((getFdyy() == null) ? 0 : getFdyy().hashCode());
		result = prime * result + ((getZrky() == null) ? 0 : getZrky().hashCode());
		result = prime * result + ((getFzrky() == null) ? 0 : getFzrky().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		result = prime * result + ((getApprovalStatus() == null) ? 0 : getApprovalStatus().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table j_org_info
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", orgId=").append(orgId);
		sb.append(", orgType=").append(orgType);
		sb.append(", areaCode=").append(areaCode);
		sb.append(", parentOrgId=").append(parentOrgId);
		sb.append(", sortSerialNo=").append(sortSerialNo);
		sb.append(", orgEncode=").append(orgEncode);
		sb.append(", orgName=").append(orgName);
		sb.append(", orgNamePy=").append(orgNamePy);
		sb.append(", otherName=").append(otherName);
		sb.append(", otherNamePy=").append(otherNamePy);
		sb.append(", orgShortName=").append(orgShortName);
		sb.append(", orgPropertyId=").append(orgPropertyId);
		sb.append(", orgShortNamePy=").append(orgShortNamePy);
		sb.append(", systemTypeId=").append(systemTypeId);
		sb.append(", orgLevelId=").append(orgLevelId);
		sb.append(", orgCategoryId=").append(orgCategoryId);
		sb.append(", orgCategorySubId=").append(orgCategorySubId);
		sb.append(", departmentId=").append(departmentId);
		sb.append(", industryClassSubId=").append(industryClassSubId);
		sb.append(", industryClassId=").append(industryClassId);
		sb.append(", orgAttrId=").append(orgAttrId);
		sb.append(", orgSortId=").append(orgSortId);
		sb.append(", orgSortSubId=").append(orgSortSubId);
		sb.append(", outlayShapeId=").append(outlayShapeId);
		sb.append(", financeBudgetCode=").append(financeBudgetCode);
		sb.append(", isPublic=").append(isPublic);
		sb.append(", isDevelopmentAreaOrg=").append(isDevelopmentAreaOrg);
		sb.append(", cangongPiwen=").append(cangongPiwen);
		sb.append(", establishmentDate=").append(establishmentDate);
		sb.append(", telphone=").append(telphone);
		sb.append(", postCode=").append(postCode);
		sb.append(", domainZh=").append(domainZh);
		sb.append(", domainEn=").append(domainEn);
		sb.append(", address=").append(address);
		sb.append(", remark=").append(remark);
		sb.append(", orgCode=").append(orgCode);
		sb.append(", legalPersonCertificateNo=").append(legalPersonCertificateNo);
		sb.append(", cangongStatus=").append(cangongStatus);
		sb.append(", orgMainObligationId=").append(orgMainObligationId);
		sb.append(", innerOrgCount=").append(innerOrgCount);
		sb.append(", otherOrgCount=").append(otherOrgCount);
		sb.append(", xzQebkCount=").append(xzQebkCount);
		sb.append(", gqCebtCount=").append(gqCebtCount);
		sb.append(", otherZszzCount=").append(otherZszzCount);
		sb.append(", deptLeaderCount=").append(deptLeaderCount);
		sb.append(", deptLeaderHighCount=").append(deptLeaderHighCount);
		sb.append(", deptViceLeadCount=").append(deptViceLeadCount);
		sb.append(", deptViceLeadHighCount=").append(deptViceLeadHighCount);
		sb.append(", inspectDisciplineCount=").append(inspectDisciplineCount);
		sb.append(", otherCount=").append(otherCount);
		sb.append(", innerLeaderCount=").append(innerLeaderCount);
		sb.append(", innerLeaderHighCount=").append(innerLeaderHighCount);
		sb.append(", innerViceLeadCount=").append(innerViceLeadCount);
		sb.append(", innerViceLeadHighCount=").append(innerViceLeadHighCount);
		sb.append(", deptNotLeaderCount=").append(deptNotLeaderCount);
		sb.append(", deptNotViceLeadCount=").append(deptNotViceLeadCount);
		sb.append(", innerNotLeadCount=").append(innerNotLeadCount);
		sb.append(", innerNotViceLeadCount=").append(innerNotViceLeadCount);
		sb.append(", managerCount=").append(managerCount);
		sb.append(", professionalSkillCount=").append(professionalSkillCount);
		sb.append(", gongqingSkillCount=").append(gongqingSkillCount);
		sb.append(", specialCount=").append(specialCount);
		sb.append(", piwenId=").append(piwenId);
		sb.append(", pwCode=").append(pwCode);
		sb.append(", status=").append(status);
		sb.append(", createtime=").append(createtime);
		sb.append(", sbjfz=").append(sbjfz);
		sb.append(", tjjzz=").append(tjjzz);
		sb.append(", tjjfz=").append(tjjfz);
		sb.append(", xcjzz=").append(xcjzz);
		sb.append(", xcjfz=").append(xcjfz);
		sb.append(", xkjzz=").append(xkjzz);
		sb.append(", xkjfz=").append(xkjfz);
		sb.append(", gjzz=").append(gjzz);
		sb.append(", gjfz=").append(gjfz);
		sb.append(", wdj=").append(wdj);
		sb.append(", qt=").append(qt);
		sb.append(", xsy=").append(xsy);
		sb.append(", fxsy=").append(fxsy);
		sb.append(", dyy=").append(dyy);
		sb.append(", fdyy=").append(fdyy);
		sb.append(", zrky=").append(zrky);
		sb.append(", fzrky=").append(fzrky);
		sb.append(", approvalStatus=").append(approvalStatus);
		sb.append("]");
		return sb.toString();
	}
}