package com.test.ado.mapper;

import com.test.vo.entity.JOrgInfo;

public interface JOrgInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table j_org_info
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String orgId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table j_org_info
	 * @mbg.generated
	 */
	int insert(JOrgInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table j_org_info
	 * @mbg.generated
	 */
	int insertSelective(JOrgInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table j_org_info
	 * @mbg.generated
	 */
	JOrgInfo selectByPrimaryKey(String orgId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table j_org_info
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(JOrgInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table j_org_info
	 * @mbg.generated
	 */
	int updateByPrimaryKey(JOrgInfo record);
}