package com.wave.base.vo.entity;

import com.wave.base.vo.BaseVo;
import java.io.Serializable;
import java.util.Date;

public class Equotetarget extends BaseVo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUOTETARGET.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUOTETARGET.QUOTEID
     *
     * @mbg.generated
     */
    private Integer quoteid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUOTETARGET.CORPID
     *
     * @mbg.generated
     */
    private Integer corpid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUOTETARGET.ATTRIBUTE1
     *
     * @mbg.generated
     */
    private String attribute1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUOTETARGET.ATTRIBUTE2
     *
     * @mbg.generated
     */
    private String attribute2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUOTETARGET.ATTRIBUTE3
     *
     * @mbg.generated
     */
    private String attribute3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUOTETARGET.CREATEDBY
     *
     * @mbg.generated
     */
    private String createdby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUOTETARGET.CREATIONDATE
     *
     * @mbg.generated
     */
    private Date creationdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUOTETARGET.LASTUPDATEBY
     *
     * @mbg.generated
     */
    private String lastupdateby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUOTETARGET.LASTUPDATEDATE
     *
     * @mbg.generated
     */
    private Date lastupdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table EQUOTETARGET
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 4934676238107849831L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUOTETARGET.ID
     *
     * @return the value of EQUOTETARGET.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUOTETARGET.ID
     *
     * @param id the value for EQUOTETARGET.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUOTETARGET.QUOTEID
     *
     * @return the value of EQUOTETARGET.QUOTEID
     *
     * @mbg.generated
     */
    public Integer getQuoteid() {
        return quoteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUOTETARGET.QUOTEID
     *
     * @param quoteid the value for EQUOTETARGET.QUOTEID
     *
     * @mbg.generated
     */
    public void setQuoteid(Integer quoteid) {
        this.quoteid = quoteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUOTETARGET.CORPID
     *
     * @return the value of EQUOTETARGET.CORPID
     *
     * @mbg.generated
     */
    public Integer getCorpid() {
        return corpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUOTETARGET.CORPID
     *
     * @param corpid the value for EQUOTETARGET.CORPID
     *
     * @mbg.generated
     */
    public void setCorpid(Integer corpid) {
        this.corpid = corpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUOTETARGET.ATTRIBUTE1
     *
     * @return the value of EQUOTETARGET.ATTRIBUTE1
     *
     * @mbg.generated
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUOTETARGET.ATTRIBUTE1
     *
     * @param attribute1 the value for EQUOTETARGET.ATTRIBUTE1
     *
     * @mbg.generated
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1 == null ? null : attribute1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUOTETARGET.ATTRIBUTE2
     *
     * @return the value of EQUOTETARGET.ATTRIBUTE2
     *
     * @mbg.generated
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUOTETARGET.ATTRIBUTE2
     *
     * @param attribute2 the value for EQUOTETARGET.ATTRIBUTE2
     *
     * @mbg.generated
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2 == null ? null : attribute2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUOTETARGET.ATTRIBUTE3
     *
     * @return the value of EQUOTETARGET.ATTRIBUTE3
     *
     * @mbg.generated
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUOTETARGET.ATTRIBUTE3
     *
     * @param attribute3 the value for EQUOTETARGET.ATTRIBUTE3
     *
     * @mbg.generated
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3 == null ? null : attribute3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUOTETARGET.CREATEDBY
     *
     * @return the value of EQUOTETARGET.CREATEDBY
     *
     * @mbg.generated
     */
    public String getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUOTETARGET.CREATEDBY
     *
     * @param createdby the value for EQUOTETARGET.CREATEDBY
     *
     * @mbg.generated
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby == null ? null : createdby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUOTETARGET.CREATIONDATE
     *
     * @return the value of EQUOTETARGET.CREATIONDATE
     *
     * @mbg.generated
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUOTETARGET.CREATIONDATE
     *
     * @param creationdate the value for EQUOTETARGET.CREATIONDATE
     *
     * @mbg.generated
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUOTETARGET.LASTUPDATEBY
     *
     * @return the value of EQUOTETARGET.LASTUPDATEBY
     *
     * @mbg.generated
     */
    public String getLastupdateby() {
        return lastupdateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUOTETARGET.LASTUPDATEBY
     *
     * @param lastupdateby the value for EQUOTETARGET.LASTUPDATEBY
     *
     * @mbg.generated
     */
    public void setLastupdateby(String lastupdateby) {
        this.lastupdateby = lastupdateby == null ? null : lastupdateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUOTETARGET.LASTUPDATEDATE
     *
     * @return the value of EQUOTETARGET.LASTUPDATEDATE
     *
     * @mbg.generated
     */
    public Date getLastupdatedate() {
        return lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUOTETARGET.LASTUPDATEDATE
     *
     * @param lastupdatedate the value for EQUOTETARGET.LASTUPDATEDATE
     *
     * @mbg.generated
     */
    public void setLastupdatedate(Date lastupdatedate) {
        this.lastupdatedate = lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUOTETARGET
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Equotetarget other = (Equotetarget) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getQuoteid() == null ? other.getQuoteid() == null : this.getQuoteid().equals(other.getQuoteid()))
            && (this.getCorpid() == null ? other.getCorpid() == null : this.getCorpid().equals(other.getCorpid()))
            && (this.getAttribute1() == null ? other.getAttribute1() == null : this.getAttribute1().equals(other.getAttribute1()))
            && (this.getAttribute2() == null ? other.getAttribute2() == null : this.getAttribute2().equals(other.getAttribute2()))
            && (this.getAttribute3() == null ? other.getAttribute3() == null : this.getAttribute3().equals(other.getAttribute3()))
            && (this.getCreatedby() == null ? other.getCreatedby() == null : this.getCreatedby().equals(other.getCreatedby()))
            && (this.getCreationdate() == null ? other.getCreationdate() == null : this.getCreationdate().equals(other.getCreationdate()))
            && (this.getLastupdateby() == null ? other.getLastupdateby() == null : this.getLastupdateby().equals(other.getLastupdateby()))
            && (this.getLastupdatedate() == null ? other.getLastupdatedate() == null : this.getLastupdatedate().equals(other.getLastupdatedate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUOTETARGET
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getQuoteid() == null) ? 0 : getQuoteid().hashCode());
        result = prime * result + ((getCorpid() == null) ? 0 : getCorpid().hashCode());
        result = prime * result + ((getAttribute1() == null) ? 0 : getAttribute1().hashCode());
        result = prime * result + ((getAttribute2() == null) ? 0 : getAttribute2().hashCode());
        result = prime * result + ((getAttribute3() == null) ? 0 : getAttribute3().hashCode());
        result = prime * result + ((getCreatedby() == null) ? 0 : getCreatedby().hashCode());
        result = prime * result + ((getCreationdate() == null) ? 0 : getCreationdate().hashCode());
        result = prime * result + ((getLastupdateby() == null) ? 0 : getLastupdateby().hashCode());
        result = prime * result + ((getLastupdatedate() == null) ? 0 : getLastupdatedate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUOTETARGET
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", quoteid=").append(quoteid);
        sb.append(", corpid=").append(corpid);
        sb.append(", attribute1=").append(attribute1);
        sb.append(", attribute2=").append(attribute2);
        sb.append(", attribute3=").append(attribute3);
        sb.append(", createdby=").append(createdby);
        sb.append(", creationdate=").append(creationdate);
        sb.append(", lastupdateby=").append(lastupdateby);
        sb.append(", lastupdatedate=").append(lastupdatedate);
        sb.append("]");
        return sb.toString();
    }
}