package com.wave.base.vo.entity;

import com.wave.base.vo.BaseVo;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SyscorpinforExample extends BaseVo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSCORPINFOR
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSCORPINFOR
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSCORPINFOR
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSCORPINFOR
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 4934676238107849831L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCORPINFOR
     *
     * @mbg.generated
     */
    public SyscorpinforExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCORPINFOR
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCORPINFOR
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCORPINFOR
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCORPINFOR
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCORPINFOR
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCORPINFOR
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCORPINFOR
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCORPINFOR
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCORPINFOR
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCORPINFOR
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYSCORPINFOR
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCorpcodeIsNull() {
            addCriterion("CORPCODE is null");
            return (Criteria) this;
        }

        public Criteria andCorpcodeIsNotNull() {
            addCriterion("CORPCODE is not null");
            return (Criteria) this;
        }

        public Criteria andCorpcodeEqualTo(String value) {
            addCriterion("CORPCODE =", value, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeNotEqualTo(String value) {
            addCriterion("CORPCODE <>", value, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeGreaterThan(String value) {
            addCriterion("CORPCODE >", value, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeGreaterThanOrEqualTo(String value) {
            addCriterion("CORPCODE >=", value, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeLessThan(String value) {
            addCriterion("CORPCODE <", value, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeLessThanOrEqualTo(String value) {
            addCriterion("CORPCODE <=", value, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeLike(String value) {
            addCriterion("CORPCODE like", value, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeNotLike(String value) {
            addCriterion("CORPCODE not like", value, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeIn(List<String> values) {
            addCriterion("CORPCODE in", values, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeNotIn(List<String> values) {
            addCriterion("CORPCODE not in", values, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeBetween(String value1, String value2) {
            addCriterion("CORPCODE between", value1, value2, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeNotBetween(String value1, String value2) {
            addCriterion("CORPCODE not between", value1, value2, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpnameIsNull() {
            addCriterion("CORPNAME is null");
            return (Criteria) this;
        }

        public Criteria andCorpnameIsNotNull() {
            addCriterion("CORPNAME is not null");
            return (Criteria) this;
        }

        public Criteria andCorpnameEqualTo(String value) {
            addCriterion("CORPNAME =", value, "corpname");
            return (Criteria) this;
        }

        public Criteria andCorpnameNotEqualTo(String value) {
            addCriterion("CORPNAME <>", value, "corpname");
            return (Criteria) this;
        }

        public Criteria andCorpnameGreaterThan(String value) {
            addCriterion("CORPNAME >", value, "corpname");
            return (Criteria) this;
        }

        public Criteria andCorpnameGreaterThanOrEqualTo(String value) {
            addCriterion("CORPNAME >=", value, "corpname");
            return (Criteria) this;
        }

        public Criteria andCorpnameLessThan(String value) {
            addCriterion("CORPNAME <", value, "corpname");
            return (Criteria) this;
        }

        public Criteria andCorpnameLessThanOrEqualTo(String value) {
            addCriterion("CORPNAME <=", value, "corpname");
            return (Criteria) this;
        }

        public Criteria andCorpnameLike(String value) {
            addCriterion("CORPNAME like", value, "corpname");
            return (Criteria) this;
        }

        public Criteria andCorpnameNotLike(String value) {
            addCriterion("CORPNAME not like", value, "corpname");
            return (Criteria) this;
        }

        public Criteria andCorpnameIn(List<String> values) {
            addCriterion("CORPNAME in", values, "corpname");
            return (Criteria) this;
        }

        public Criteria andCorpnameNotIn(List<String> values) {
            addCriterion("CORPNAME not in", values, "corpname");
            return (Criteria) this;
        }

        public Criteria andCorpnameBetween(String value1, String value2) {
            addCriterion("CORPNAME between", value1, value2, "corpname");
            return (Criteria) this;
        }

        public Criteria andCorpnameNotBetween(String value1, String value2) {
            addCriterion("CORPNAME not between", value1, value2, "corpname");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameIsNull() {
            addCriterion("CORPSHORTNAME is null");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameIsNotNull() {
            addCriterion("CORPSHORTNAME is not null");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameEqualTo(String value) {
            addCriterion("CORPSHORTNAME =", value, "corpshortname");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameNotEqualTo(String value) {
            addCriterion("CORPSHORTNAME <>", value, "corpshortname");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameGreaterThan(String value) {
            addCriterion("CORPSHORTNAME >", value, "corpshortname");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameGreaterThanOrEqualTo(String value) {
            addCriterion("CORPSHORTNAME >=", value, "corpshortname");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameLessThan(String value) {
            addCriterion("CORPSHORTNAME <", value, "corpshortname");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameLessThanOrEqualTo(String value) {
            addCriterion("CORPSHORTNAME <=", value, "corpshortname");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameLike(String value) {
            addCriterion("CORPSHORTNAME like", value, "corpshortname");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameNotLike(String value) {
            addCriterion("CORPSHORTNAME not like", value, "corpshortname");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameIn(List<String> values) {
            addCriterion("CORPSHORTNAME in", values, "corpshortname");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameNotIn(List<String> values) {
            addCriterion("CORPSHORTNAME not in", values, "corpshortname");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameBetween(String value1, String value2) {
            addCriterion("CORPSHORTNAME between", value1, value2, "corpshortname");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameNotBetween(String value1, String value2) {
            addCriterion("CORPSHORTNAME not between", value1, value2, "corpshortname");
            return (Criteria) this;
        }

        public Criteria andCorptypeIsNull() {
            addCriterion("CORPTYPE is null");
            return (Criteria) this;
        }

        public Criteria andCorptypeIsNotNull() {
            addCriterion("CORPTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCorptypeEqualTo(String value) {
            addCriterion("CORPTYPE =", value, "corptype");
            return (Criteria) this;
        }

        public Criteria andCorptypeNotEqualTo(String value) {
            addCriterion("CORPTYPE <>", value, "corptype");
            return (Criteria) this;
        }

        public Criteria andCorptypeGreaterThan(String value) {
            addCriterion("CORPTYPE >", value, "corptype");
            return (Criteria) this;
        }

        public Criteria andCorptypeGreaterThanOrEqualTo(String value) {
            addCriterion("CORPTYPE >=", value, "corptype");
            return (Criteria) this;
        }

        public Criteria andCorptypeLessThan(String value) {
            addCriterion("CORPTYPE <", value, "corptype");
            return (Criteria) this;
        }

        public Criteria andCorptypeLessThanOrEqualTo(String value) {
            addCriterion("CORPTYPE <=", value, "corptype");
            return (Criteria) this;
        }

        public Criteria andCorptypeLike(String value) {
            addCriterion("CORPTYPE like", value, "corptype");
            return (Criteria) this;
        }

        public Criteria andCorptypeNotLike(String value) {
            addCriterion("CORPTYPE not like", value, "corptype");
            return (Criteria) this;
        }

        public Criteria andCorptypeIn(List<String> values) {
            addCriterion("CORPTYPE in", values, "corptype");
            return (Criteria) this;
        }

        public Criteria andCorptypeNotIn(List<String> values) {
            addCriterion("CORPTYPE not in", values, "corptype");
            return (Criteria) this;
        }

        public Criteria andCorptypeBetween(String value1, String value2) {
            addCriterion("CORPTYPE between", value1, value2, "corptype");
            return (Criteria) this;
        }

        public Criteria andCorptypeNotBetween(String value1, String value2) {
            addCriterion("CORPTYPE not between", value1, value2, "corptype");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("PASSWORD =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("PASSWORD <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("PASSWORD >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("PASSWORD >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("PASSWORD <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("PASSWORD <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("PASSWORD like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("PASSWORD not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("PASSWORD in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("PASSWORD not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("PASSWORD between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("PASSWORD not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andUserloginnameIsNull() {
            addCriterion("USERLOGINNAME is null");
            return (Criteria) this;
        }

        public Criteria andUserloginnameIsNotNull() {
            addCriterion("USERLOGINNAME is not null");
            return (Criteria) this;
        }

        public Criteria andUserloginnameEqualTo(String value) {
            addCriterion("USERLOGINNAME =", value, "userloginname");
            return (Criteria) this;
        }

        public Criteria andUserloginnameNotEqualTo(String value) {
            addCriterion("USERLOGINNAME <>", value, "userloginname");
            return (Criteria) this;
        }

        public Criteria andUserloginnameGreaterThan(String value) {
            addCriterion("USERLOGINNAME >", value, "userloginname");
            return (Criteria) this;
        }

        public Criteria andUserloginnameGreaterThanOrEqualTo(String value) {
            addCriterion("USERLOGINNAME >=", value, "userloginname");
            return (Criteria) this;
        }

        public Criteria andUserloginnameLessThan(String value) {
            addCriterion("USERLOGINNAME <", value, "userloginname");
            return (Criteria) this;
        }

        public Criteria andUserloginnameLessThanOrEqualTo(String value) {
            addCriterion("USERLOGINNAME <=", value, "userloginname");
            return (Criteria) this;
        }

        public Criteria andUserloginnameLike(String value) {
            addCriterion("USERLOGINNAME like", value, "userloginname");
            return (Criteria) this;
        }

        public Criteria andUserloginnameNotLike(String value) {
            addCriterion("USERLOGINNAME not like", value, "userloginname");
            return (Criteria) this;
        }

        public Criteria andUserloginnameIn(List<String> values) {
            addCriterion("USERLOGINNAME in", values, "userloginname");
            return (Criteria) this;
        }

        public Criteria andUserloginnameNotIn(List<String> values) {
            addCriterion("USERLOGINNAME not in", values, "userloginname");
            return (Criteria) this;
        }

        public Criteria andUserloginnameBetween(String value1, String value2) {
            addCriterion("USERLOGINNAME between", value1, value2, "userloginname");
            return (Criteria) this;
        }

        public Criteria andUserloginnameNotBetween(String value1, String value2) {
            addCriterion("USERLOGINNAME not between", value1, value2, "userloginname");
            return (Criteria) this;
        }

        public Criteria andAttribute2IsNull() {
            addCriterion("ATTRIBUTE2 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute2IsNotNull() {
            addCriterion("ATTRIBUTE2 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute2EqualTo(String value) {
            addCriterion("ATTRIBUTE2 =", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2NotEqualTo(String value) {
            addCriterion("ATTRIBUTE2 <>", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2GreaterThan(String value) {
            addCriterion("ATTRIBUTE2 >", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2GreaterThanOrEqualTo(String value) {
            addCriterion("ATTRIBUTE2 >=", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2LessThan(String value) {
            addCriterion("ATTRIBUTE2 <", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2LessThanOrEqualTo(String value) {
            addCriterion("ATTRIBUTE2 <=", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2Like(String value) {
            addCriterion("ATTRIBUTE2 like", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2NotLike(String value) {
            addCriterion("ATTRIBUTE2 not like", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2In(List<String> values) {
            addCriterion("ATTRIBUTE2 in", values, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2NotIn(List<String> values) {
            addCriterion("ATTRIBUTE2 not in", values, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2Between(String value1, String value2) {
            addCriterion("ATTRIBUTE2 between", value1, value2, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2NotBetween(String value1, String value2) {
            addCriterion("ATTRIBUTE2 not between", value1, value2, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute3IsNull() {
            addCriterion("ATTRIBUTE3 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute3IsNotNull() {
            addCriterion("ATTRIBUTE3 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute3EqualTo(String value) {
            addCriterion("ATTRIBUTE3 =", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3NotEqualTo(String value) {
            addCriterion("ATTRIBUTE3 <>", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3GreaterThan(String value) {
            addCriterion("ATTRIBUTE3 >", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3GreaterThanOrEqualTo(String value) {
            addCriterion("ATTRIBUTE3 >=", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3LessThan(String value) {
            addCriterion("ATTRIBUTE3 <", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3LessThanOrEqualTo(String value) {
            addCriterion("ATTRIBUTE3 <=", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3Like(String value) {
            addCriterion("ATTRIBUTE3 like", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3NotLike(String value) {
            addCriterion("ATTRIBUTE3 not like", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3In(List<String> values) {
            addCriterion("ATTRIBUTE3 in", values, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3NotIn(List<String> values) {
            addCriterion("ATTRIBUTE3 not in", values, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3Between(String value1, String value2) {
            addCriterion("ATTRIBUTE3 between", value1, value2, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3NotBetween(String value1, String value2) {
            addCriterion("ATTRIBUTE3 not between", value1, value2, "attribute3");
            return (Criteria) this;
        }

        public Criteria andCreatedbyIsNull() {
            addCriterion("CREATEDBY is null");
            return (Criteria) this;
        }

        public Criteria andCreatedbyIsNotNull() {
            addCriterion("CREATEDBY is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedbyEqualTo(String value) {
            addCriterion("CREATEDBY =", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyNotEqualTo(String value) {
            addCriterion("CREATEDBY <>", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyGreaterThan(String value) {
            addCriterion("CREATEDBY >", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEDBY >=", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyLessThan(String value) {
            addCriterion("CREATEDBY <", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyLessThanOrEqualTo(String value) {
            addCriterion("CREATEDBY <=", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyLike(String value) {
            addCriterion("CREATEDBY like", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyNotLike(String value) {
            addCriterion("CREATEDBY not like", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyIn(List<String> values) {
            addCriterion("CREATEDBY in", values, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyNotIn(List<String> values) {
            addCriterion("CREATEDBY not in", values, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyBetween(String value1, String value2) {
            addCriterion("CREATEDBY between", value1, value2, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyNotBetween(String value1, String value2) {
            addCriterion("CREATEDBY not between", value1, value2, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreationdateIsNull() {
            addCriterion("CREATIONDATE is null");
            return (Criteria) this;
        }

        public Criteria andCreationdateIsNotNull() {
            addCriterion("CREATIONDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreationdateEqualTo(Date value) {
            addCriterion("CREATIONDATE =", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateNotEqualTo(Date value) {
            addCriterion("CREATIONDATE <>", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateGreaterThan(Date value) {
            addCriterion("CREATIONDATE >", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATIONDATE >=", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateLessThan(Date value) {
            addCriterion("CREATIONDATE <", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateLessThanOrEqualTo(Date value) {
            addCriterion("CREATIONDATE <=", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateIn(List<Date> values) {
            addCriterion("CREATIONDATE in", values, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateNotIn(List<Date> values) {
            addCriterion("CREATIONDATE not in", values, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateBetween(Date value1, Date value2) {
            addCriterion("CREATIONDATE between", value1, value2, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateNotBetween(Date value1, Date value2) {
            addCriterion("CREATIONDATE not between", value1, value2, "creationdate");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyIsNull() {
            addCriterion("LASTUPDATEBY is null");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyIsNotNull() {
            addCriterion("LASTUPDATEBY is not null");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyEqualTo(String value) {
            addCriterion("LASTUPDATEBY =", value, "lastupdateby");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyNotEqualTo(String value) {
            addCriterion("LASTUPDATEBY <>", value, "lastupdateby");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyGreaterThan(String value) {
            addCriterion("LASTUPDATEBY >", value, "lastupdateby");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyGreaterThanOrEqualTo(String value) {
            addCriterion("LASTUPDATEBY >=", value, "lastupdateby");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyLessThan(String value) {
            addCriterion("LASTUPDATEBY <", value, "lastupdateby");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyLessThanOrEqualTo(String value) {
            addCriterion("LASTUPDATEBY <=", value, "lastupdateby");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyLike(String value) {
            addCriterion("LASTUPDATEBY like", value, "lastupdateby");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyNotLike(String value) {
            addCriterion("LASTUPDATEBY not like", value, "lastupdateby");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyIn(List<String> values) {
            addCriterion("LASTUPDATEBY in", values, "lastupdateby");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyNotIn(List<String> values) {
            addCriterion("LASTUPDATEBY not in", values, "lastupdateby");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyBetween(String value1, String value2) {
            addCriterion("LASTUPDATEBY between", value1, value2, "lastupdateby");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyNotBetween(String value1, String value2) {
            addCriterion("LASTUPDATEBY not between", value1, value2, "lastupdateby");
            return (Criteria) this;
        }

        public Criteria andLastupdatedateIsNull() {
            addCriterion("LASTUPDATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andLastupdatedateIsNotNull() {
            addCriterion("LASTUPDATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andLastupdatedateEqualTo(Date value) {
            addCriterion("LASTUPDATEDATE =", value, "lastupdatedate");
            return (Criteria) this;
        }

        public Criteria andLastupdatedateNotEqualTo(Date value) {
            addCriterion("LASTUPDATEDATE <>", value, "lastupdatedate");
            return (Criteria) this;
        }

        public Criteria andLastupdatedateGreaterThan(Date value) {
            addCriterion("LASTUPDATEDATE >", value, "lastupdatedate");
            return (Criteria) this;
        }

        public Criteria andLastupdatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("LASTUPDATEDATE >=", value, "lastupdatedate");
            return (Criteria) this;
        }

        public Criteria andLastupdatedateLessThan(Date value) {
            addCriterion("LASTUPDATEDATE <", value, "lastupdatedate");
            return (Criteria) this;
        }

        public Criteria andLastupdatedateLessThanOrEqualTo(Date value) {
            addCriterion("LASTUPDATEDATE <=", value, "lastupdatedate");
            return (Criteria) this;
        }

        public Criteria andLastupdatedateIn(List<Date> values) {
            addCriterion("LASTUPDATEDATE in", values, "lastupdatedate");
            return (Criteria) this;
        }

        public Criteria andLastupdatedateNotIn(List<Date> values) {
            addCriterion("LASTUPDATEDATE not in", values, "lastupdatedate");
            return (Criteria) this;
        }

        public Criteria andLastupdatedateBetween(Date value1, Date value2) {
            addCriterion("LASTUPDATEDATE between", value1, value2, "lastupdatedate");
            return (Criteria) this;
        }

        public Criteria andLastupdatedateNotBetween(Date value1, Date value2) {
            addCriterion("LASTUPDATEDATE not between", value1, value2, "lastupdatedate");
            return (Criteria) this;
        }

        public Criteria andCorpcodeLikeInsensitive(String value) {
            addCriterion("upper(CORPCODE) like", value.toUpperCase(), "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpnameLikeInsensitive(String value) {
            addCriterion("upper(CORPNAME) like", value.toUpperCase(), "corpname");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameLikeInsensitive(String value) {
            addCriterion("upper(CORPSHORTNAME) like", value.toUpperCase(), "corpshortname");
            return (Criteria) this;
        }

        public Criteria andCorptypeLikeInsensitive(String value) {
            addCriterion("upper(CORPTYPE) like", value.toUpperCase(), "corptype");
            return (Criteria) this;
        }

        public Criteria andPasswordLikeInsensitive(String value) {
            addCriterion("upper(PASSWORD) like", value.toUpperCase(), "password");
            return (Criteria) this;
        }

        public Criteria andStatusLikeInsensitive(String value) {
            addCriterion("upper(STATUS) like", value.toUpperCase(), "status");
            return (Criteria) this;
        }

        public Criteria andUserloginnameLikeInsensitive(String value) {
            addCriterion("upper(USERLOGINNAME) like", value.toUpperCase(), "userloginname");
            return (Criteria) this;
        }

        public Criteria andAttribute2LikeInsensitive(String value) {
            addCriterion("upper(ATTRIBUTE2) like", value.toUpperCase(), "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute3LikeInsensitive(String value) {
            addCriterion("upper(ATTRIBUTE3) like", value.toUpperCase(), "attribute3");
            return (Criteria) this;
        }

        public Criteria andCreatedbyLikeInsensitive(String value) {
            addCriterion("upper(CREATEDBY) like", value.toUpperCase(), "createdby");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyLikeInsensitive(String value) {
            addCriterion("upper(LASTUPDATEBY) like", value.toUpperCase(), "lastupdateby");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYSCORPINFOR
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYSCORPINFOR
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}