package com.wave.base.vo.entity;

import com.wave.base.vo.BaseVo;
import java.io.Serializable;
import java.util.Date;

public class VEqinquiry extends BaseVo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_eqinquiry.corpCode
     *
     * @mbg.generated
     */
    private String corpcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_eqinquiry.corpName
     *
     * @mbg.generated
     */
    private String corpname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_eqinquiry.corpShortName
     *
     * @mbg.generated
     */
    private String corpshortname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_eqinquiry.corpType
     *
     * @mbg.generated
     */
    private String corptype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_eqinquiry.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_eqinquiry.corpId
     *
     * @mbg.generated
     */
    private Integer corpid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_eqinquiry.inquiryContent
     *
     * @mbg.generated
     */
    private String inquirycontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_eqinquiry.inquiryDate
     *
     * @mbg.generated
     */
    private Date inquirydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_eqinquiry.attribute1
     *
     * @mbg.generated
     */
    private String attribute1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_eqinquiry.attribute2
     *
     * @mbg.generated
     */
    private String attribute2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_eqinquiry.attribute3
     *
     * @mbg.generated
     */
    private String attribute3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_eqinquiry.createdBy
     *
     * @mbg.generated
     */
    private String createdby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_eqinquiry.creationDate
     *
     * @mbg.generated
     */
    private Date creationdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_eqinquiry.lastUpdateBy
     *
     * @mbg.generated
     */
    private String lastupdateby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_eqinquiry.lastUpdateDate
     *
     * @mbg.generated
     */
    private Date lastupdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_eqinquiry
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 4934676238107849831L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_eqinquiry.corpCode
     *
     * @return the value of v_eqinquiry.corpCode
     *
     * @mbg.generated
     */
    public String getCorpcode() {
        return corpcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_eqinquiry.corpCode
     *
     * @param corpcode the value for v_eqinquiry.corpCode
     *
     * @mbg.generated
     */
    public void setCorpcode(String corpcode) {
        this.corpcode = corpcode == null ? null : corpcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_eqinquiry.corpName
     *
     * @return the value of v_eqinquiry.corpName
     *
     * @mbg.generated
     */
    public String getCorpname() {
        return corpname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_eqinquiry.corpName
     *
     * @param corpname the value for v_eqinquiry.corpName
     *
     * @mbg.generated
     */
    public void setCorpname(String corpname) {
        this.corpname = corpname == null ? null : corpname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_eqinquiry.corpShortName
     *
     * @return the value of v_eqinquiry.corpShortName
     *
     * @mbg.generated
     */
    public String getCorpshortname() {
        return corpshortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_eqinquiry.corpShortName
     *
     * @param corpshortname the value for v_eqinquiry.corpShortName
     *
     * @mbg.generated
     */
    public void setCorpshortname(String corpshortname) {
        this.corpshortname = corpshortname == null ? null : corpshortname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_eqinquiry.corpType
     *
     * @return the value of v_eqinquiry.corpType
     *
     * @mbg.generated
     */
    public String getCorptype() {
        return corptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_eqinquiry.corpType
     *
     * @param corptype the value for v_eqinquiry.corpType
     *
     * @mbg.generated
     */
    public void setCorptype(String corptype) {
        this.corptype = corptype == null ? null : corptype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_eqinquiry.id
     *
     * @return the value of v_eqinquiry.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_eqinquiry.id
     *
     * @param id the value for v_eqinquiry.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_eqinquiry.corpId
     *
     * @return the value of v_eqinquiry.corpId
     *
     * @mbg.generated
     */
    public Integer getCorpid() {
        return corpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_eqinquiry.corpId
     *
     * @param corpid the value for v_eqinquiry.corpId
     *
     * @mbg.generated
     */
    public void setCorpid(Integer corpid) {
        this.corpid = corpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_eqinquiry.inquiryContent
     *
     * @return the value of v_eqinquiry.inquiryContent
     *
     * @mbg.generated
     */
    public String getInquirycontent() {
        return inquirycontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_eqinquiry.inquiryContent
     *
     * @param inquirycontent the value for v_eqinquiry.inquiryContent
     *
     * @mbg.generated
     */
    public void setInquirycontent(String inquirycontent) {
        this.inquirycontent = inquirycontent == null ? null : inquirycontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_eqinquiry.inquiryDate
     *
     * @return the value of v_eqinquiry.inquiryDate
     *
     * @mbg.generated
     */
    public Date getInquirydate() {
        return inquirydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_eqinquiry.inquiryDate
     *
     * @param inquirydate the value for v_eqinquiry.inquiryDate
     *
     * @mbg.generated
     */
    public void setInquirydate(Date inquirydate) {
        this.inquirydate = inquirydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_eqinquiry.attribute1
     *
     * @return the value of v_eqinquiry.attribute1
     *
     * @mbg.generated
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_eqinquiry.attribute1
     *
     * @param attribute1 the value for v_eqinquiry.attribute1
     *
     * @mbg.generated
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1 == null ? null : attribute1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_eqinquiry.attribute2
     *
     * @return the value of v_eqinquiry.attribute2
     *
     * @mbg.generated
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_eqinquiry.attribute2
     *
     * @param attribute2 the value for v_eqinquiry.attribute2
     *
     * @mbg.generated
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2 == null ? null : attribute2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_eqinquiry.attribute3
     *
     * @return the value of v_eqinquiry.attribute3
     *
     * @mbg.generated
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_eqinquiry.attribute3
     *
     * @param attribute3 the value for v_eqinquiry.attribute3
     *
     * @mbg.generated
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3 == null ? null : attribute3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_eqinquiry.createdBy
     *
     * @return the value of v_eqinquiry.createdBy
     *
     * @mbg.generated
     */
    public String getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_eqinquiry.createdBy
     *
     * @param createdby the value for v_eqinquiry.createdBy
     *
     * @mbg.generated
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby == null ? null : createdby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_eqinquiry.creationDate
     *
     * @return the value of v_eqinquiry.creationDate
     *
     * @mbg.generated
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_eqinquiry.creationDate
     *
     * @param creationdate the value for v_eqinquiry.creationDate
     *
     * @mbg.generated
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_eqinquiry.lastUpdateBy
     *
     * @return the value of v_eqinquiry.lastUpdateBy
     *
     * @mbg.generated
     */
    public String getLastupdateby() {
        return lastupdateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_eqinquiry.lastUpdateBy
     *
     * @param lastupdateby the value for v_eqinquiry.lastUpdateBy
     *
     * @mbg.generated
     */
    public void setLastupdateby(String lastupdateby) {
        this.lastupdateby = lastupdateby == null ? null : lastupdateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_eqinquiry.lastUpdateDate
     *
     * @return the value of v_eqinquiry.lastUpdateDate
     *
     * @mbg.generated
     */
    public Date getLastupdatedate() {
        return lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_eqinquiry.lastUpdateDate
     *
     * @param lastupdatedate the value for v_eqinquiry.lastUpdateDate
     *
     * @mbg.generated
     */
    public void setLastupdatedate(Date lastupdatedate) {
        this.lastupdatedate = lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_eqinquiry
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        VEqinquiry other = (VEqinquiry) that;
        return (this.getCorpcode() == null ? other.getCorpcode() == null : this.getCorpcode().equals(other.getCorpcode()))
            && (this.getCorpname() == null ? other.getCorpname() == null : this.getCorpname().equals(other.getCorpname()))
            && (this.getCorpshortname() == null ? other.getCorpshortname() == null : this.getCorpshortname().equals(other.getCorpshortname()))
            && (this.getCorptype() == null ? other.getCorptype() == null : this.getCorptype().equals(other.getCorptype()))
            && (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCorpid() == null ? other.getCorpid() == null : this.getCorpid().equals(other.getCorpid()))
            && (this.getInquirycontent() == null ? other.getInquirycontent() == null : this.getInquirycontent().equals(other.getInquirycontent()))
            && (this.getInquirydate() == null ? other.getInquirydate() == null : this.getInquirydate().equals(other.getInquirydate()))
            && (this.getAttribute1() == null ? other.getAttribute1() == null : this.getAttribute1().equals(other.getAttribute1()))
            && (this.getAttribute2() == null ? other.getAttribute2() == null : this.getAttribute2().equals(other.getAttribute2()))
            && (this.getAttribute3() == null ? other.getAttribute3() == null : this.getAttribute3().equals(other.getAttribute3()))
            && (this.getCreatedby() == null ? other.getCreatedby() == null : this.getCreatedby().equals(other.getCreatedby()))
            && (this.getCreationdate() == null ? other.getCreationdate() == null : this.getCreationdate().equals(other.getCreationdate()))
            && (this.getLastupdateby() == null ? other.getLastupdateby() == null : this.getLastupdateby().equals(other.getLastupdateby()))
            && (this.getLastupdatedate() == null ? other.getLastupdatedate() == null : this.getLastupdatedate().equals(other.getLastupdatedate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_eqinquiry
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCorpcode() == null) ? 0 : getCorpcode().hashCode());
        result = prime * result + ((getCorpname() == null) ? 0 : getCorpname().hashCode());
        result = prime * result + ((getCorpshortname() == null) ? 0 : getCorpshortname().hashCode());
        result = prime * result + ((getCorptype() == null) ? 0 : getCorptype().hashCode());
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCorpid() == null) ? 0 : getCorpid().hashCode());
        result = prime * result + ((getInquirycontent() == null) ? 0 : getInquirycontent().hashCode());
        result = prime * result + ((getInquirydate() == null) ? 0 : getInquirydate().hashCode());
        result = prime * result + ((getAttribute1() == null) ? 0 : getAttribute1().hashCode());
        result = prime * result + ((getAttribute2() == null) ? 0 : getAttribute2().hashCode());
        result = prime * result + ((getAttribute3() == null) ? 0 : getAttribute3().hashCode());
        result = prime * result + ((getCreatedby() == null) ? 0 : getCreatedby().hashCode());
        result = prime * result + ((getCreationdate() == null) ? 0 : getCreationdate().hashCode());
        result = prime * result + ((getLastupdateby() == null) ? 0 : getLastupdateby().hashCode());
        result = prime * result + ((getLastupdatedate() == null) ? 0 : getLastupdatedate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_eqinquiry
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", corpcode=").append(corpcode);
        sb.append(", corpname=").append(corpname);
        sb.append(", corpshortname=").append(corpshortname);
        sb.append(", corptype=").append(corptype);
        sb.append(", id=").append(id);
        sb.append(", corpid=").append(corpid);
        sb.append(", inquirycontent=").append(inquirycontent);
        sb.append(", inquirydate=").append(inquirydate);
        sb.append(", attribute1=").append(attribute1);
        sb.append(", attribute2=").append(attribute2);
        sb.append(", attribute3=").append(attribute3);
        sb.append(", createdby=").append(createdby);
        sb.append(", creationdate=").append(creationdate);
        sb.append(", lastupdateby=").append(lastupdateby);
        sb.append(", lastupdatedate=").append(lastupdatedate);
        sb.append("]");
        return sb.toString();
    }
}