package com.wave.base.vo.entity;

import com.wave.base.vo.BaseVo;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VEqinquiryTargetExample extends BaseVo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_eqinquiry_target
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_eqinquiry_target
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_eqinquiry_target
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_eqinquiry_target
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 4934676238107849831L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_eqinquiry_target
     *
     * @mbg.generated
     */
    public VEqinquiryTargetExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_eqinquiry_target
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_eqinquiry_target
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_eqinquiry_target
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_eqinquiry_target
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_eqinquiry_target
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_eqinquiry_target
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_eqinquiry_target
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_eqinquiry_target
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_eqinquiry_target
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_eqinquiry_target
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table v_eqinquiry_target
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCorpcodeIsNull() {
            addCriterion("corpCode is null");
            return (Criteria) this;
        }

        public Criteria andCorpcodeIsNotNull() {
            addCriterion("corpCode is not null");
            return (Criteria) this;
        }

        public Criteria andCorpcodeEqualTo(String value) {
            addCriterion("corpCode =", value, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeNotEqualTo(String value) {
            addCriterion("corpCode <>", value, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeGreaterThan(String value) {
            addCriterion("corpCode >", value, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeGreaterThanOrEqualTo(String value) {
            addCriterion("corpCode >=", value, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeLessThan(String value) {
            addCriterion("corpCode <", value, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeLessThanOrEqualTo(String value) {
            addCriterion("corpCode <=", value, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeLike(String value) {
            addCriterion("corpCode like", value, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeNotLike(String value) {
            addCriterion("corpCode not like", value, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeIn(List<String> values) {
            addCriterion("corpCode in", values, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeNotIn(List<String> values) {
            addCriterion("corpCode not in", values, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeBetween(String value1, String value2) {
            addCriterion("corpCode between", value1, value2, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeNotBetween(String value1, String value2) {
            addCriterion("corpCode not between", value1, value2, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpnameIsNull() {
            addCriterion("corpName is null");
            return (Criteria) this;
        }

        public Criteria andCorpnameIsNotNull() {
            addCriterion("corpName is not null");
            return (Criteria) this;
        }

        public Criteria andCorpnameEqualTo(String value) {
            addCriterion("corpName =", value, "corpname");
            return (Criteria) this;
        }

        public Criteria andCorpnameNotEqualTo(String value) {
            addCriterion("corpName <>", value, "corpname");
            return (Criteria) this;
        }

        public Criteria andCorpnameGreaterThan(String value) {
            addCriterion("corpName >", value, "corpname");
            return (Criteria) this;
        }

        public Criteria andCorpnameGreaterThanOrEqualTo(String value) {
            addCriterion("corpName >=", value, "corpname");
            return (Criteria) this;
        }

        public Criteria andCorpnameLessThan(String value) {
            addCriterion("corpName <", value, "corpname");
            return (Criteria) this;
        }

        public Criteria andCorpnameLessThanOrEqualTo(String value) {
            addCriterion("corpName <=", value, "corpname");
            return (Criteria) this;
        }

        public Criteria andCorpnameLike(String value) {
            addCriterion("corpName like", value, "corpname");
            return (Criteria) this;
        }

        public Criteria andCorpnameNotLike(String value) {
            addCriterion("corpName not like", value, "corpname");
            return (Criteria) this;
        }

        public Criteria andCorpnameIn(List<String> values) {
            addCriterion("corpName in", values, "corpname");
            return (Criteria) this;
        }

        public Criteria andCorpnameNotIn(List<String> values) {
            addCriterion("corpName not in", values, "corpname");
            return (Criteria) this;
        }

        public Criteria andCorpnameBetween(String value1, String value2) {
            addCriterion("corpName between", value1, value2, "corpname");
            return (Criteria) this;
        }

        public Criteria andCorpnameNotBetween(String value1, String value2) {
            addCriterion("corpName not between", value1, value2, "corpname");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameIsNull() {
            addCriterion("corpShortName is null");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameIsNotNull() {
            addCriterion("corpShortName is not null");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameEqualTo(String value) {
            addCriterion("corpShortName =", value, "corpshortname");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameNotEqualTo(String value) {
            addCriterion("corpShortName <>", value, "corpshortname");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameGreaterThan(String value) {
            addCriterion("corpShortName >", value, "corpshortname");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameGreaterThanOrEqualTo(String value) {
            addCriterion("corpShortName >=", value, "corpshortname");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameLessThan(String value) {
            addCriterion("corpShortName <", value, "corpshortname");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameLessThanOrEqualTo(String value) {
            addCriterion("corpShortName <=", value, "corpshortname");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameLike(String value) {
            addCriterion("corpShortName like", value, "corpshortname");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameNotLike(String value) {
            addCriterion("corpShortName not like", value, "corpshortname");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameIn(List<String> values) {
            addCriterion("corpShortName in", values, "corpshortname");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameNotIn(List<String> values) {
            addCriterion("corpShortName not in", values, "corpshortname");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameBetween(String value1, String value2) {
            addCriterion("corpShortName between", value1, value2, "corpshortname");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameNotBetween(String value1, String value2) {
            addCriterion("corpShortName not between", value1, value2, "corpshortname");
            return (Criteria) this;
        }

        public Criteria andCorptypeIsNull() {
            addCriterion("corpType is null");
            return (Criteria) this;
        }

        public Criteria andCorptypeIsNotNull() {
            addCriterion("corpType is not null");
            return (Criteria) this;
        }

        public Criteria andCorptypeEqualTo(String value) {
            addCriterion("corpType =", value, "corptype");
            return (Criteria) this;
        }

        public Criteria andCorptypeNotEqualTo(String value) {
            addCriterion("corpType <>", value, "corptype");
            return (Criteria) this;
        }

        public Criteria andCorptypeGreaterThan(String value) {
            addCriterion("corpType >", value, "corptype");
            return (Criteria) this;
        }

        public Criteria andCorptypeGreaterThanOrEqualTo(String value) {
            addCriterion("corpType >=", value, "corptype");
            return (Criteria) this;
        }

        public Criteria andCorptypeLessThan(String value) {
            addCriterion("corpType <", value, "corptype");
            return (Criteria) this;
        }

        public Criteria andCorptypeLessThanOrEqualTo(String value) {
            addCriterion("corpType <=", value, "corptype");
            return (Criteria) this;
        }

        public Criteria andCorptypeLike(String value) {
            addCriterion("corpType like", value, "corptype");
            return (Criteria) this;
        }

        public Criteria andCorptypeNotLike(String value) {
            addCriterion("corpType not like", value, "corptype");
            return (Criteria) this;
        }

        public Criteria andCorptypeIn(List<String> values) {
            addCriterion("corpType in", values, "corptype");
            return (Criteria) this;
        }

        public Criteria andCorptypeNotIn(List<String> values) {
            addCriterion("corpType not in", values, "corptype");
            return (Criteria) this;
        }

        public Criteria andCorptypeBetween(String value1, String value2) {
            addCriterion("corpType between", value1, value2, "corptype");
            return (Criteria) this;
        }

        public Criteria andCorptypeNotBetween(String value1, String value2) {
            addCriterion("corpType not between", value1, value2, "corptype");
            return (Criteria) this;
        }

        public Criteria andCorpidtarIsNull() {
            addCriterion("corpIdTar is null");
            return (Criteria) this;
        }

        public Criteria andCorpidtarIsNotNull() {
            addCriterion("corpIdTar is not null");
            return (Criteria) this;
        }

        public Criteria andCorpidtarEqualTo(Integer value) {
            addCriterion("corpIdTar =", value, "corpidtar");
            return (Criteria) this;
        }

        public Criteria andCorpidtarNotEqualTo(Integer value) {
            addCriterion("corpIdTar <>", value, "corpidtar");
            return (Criteria) this;
        }

        public Criteria andCorpidtarGreaterThan(Integer value) {
            addCriterion("corpIdTar >", value, "corpidtar");
            return (Criteria) this;
        }

        public Criteria andCorpidtarGreaterThanOrEqualTo(Integer value) {
            addCriterion("corpIdTar >=", value, "corpidtar");
            return (Criteria) this;
        }

        public Criteria andCorpidtarLessThan(Integer value) {
            addCriterion("corpIdTar <", value, "corpidtar");
            return (Criteria) this;
        }

        public Criteria andCorpidtarLessThanOrEqualTo(Integer value) {
            addCriterion("corpIdTar <=", value, "corpidtar");
            return (Criteria) this;
        }

        public Criteria andCorpidtarIn(List<Integer> values) {
            addCriterion("corpIdTar in", values, "corpidtar");
            return (Criteria) this;
        }

        public Criteria andCorpidtarNotIn(List<Integer> values) {
            addCriterion("corpIdTar not in", values, "corpidtar");
            return (Criteria) this;
        }

        public Criteria andCorpidtarBetween(Integer value1, Integer value2) {
            addCriterion("corpIdTar between", value1, value2, "corpidtar");
            return (Criteria) this;
        }

        public Criteria andCorpidtarNotBetween(Integer value1, Integer value2) {
            addCriterion("corpIdTar not between", value1, value2, "corpidtar");
            return (Criteria) this;
        }

        public Criteria andCorpcodetarIsNull() {
            addCriterion("corpCodeTar is null");
            return (Criteria) this;
        }

        public Criteria andCorpcodetarIsNotNull() {
            addCriterion("corpCodeTar is not null");
            return (Criteria) this;
        }

        public Criteria andCorpcodetarEqualTo(String value) {
            addCriterion("corpCodeTar =", value, "corpcodetar");
            return (Criteria) this;
        }

        public Criteria andCorpcodetarNotEqualTo(String value) {
            addCriterion("corpCodeTar <>", value, "corpcodetar");
            return (Criteria) this;
        }

        public Criteria andCorpcodetarGreaterThan(String value) {
            addCriterion("corpCodeTar >", value, "corpcodetar");
            return (Criteria) this;
        }

        public Criteria andCorpcodetarGreaterThanOrEqualTo(String value) {
            addCriterion("corpCodeTar >=", value, "corpcodetar");
            return (Criteria) this;
        }

        public Criteria andCorpcodetarLessThan(String value) {
            addCriterion("corpCodeTar <", value, "corpcodetar");
            return (Criteria) this;
        }

        public Criteria andCorpcodetarLessThanOrEqualTo(String value) {
            addCriterion("corpCodeTar <=", value, "corpcodetar");
            return (Criteria) this;
        }

        public Criteria andCorpcodetarLike(String value) {
            addCriterion("corpCodeTar like", value, "corpcodetar");
            return (Criteria) this;
        }

        public Criteria andCorpcodetarNotLike(String value) {
            addCriterion("corpCodeTar not like", value, "corpcodetar");
            return (Criteria) this;
        }

        public Criteria andCorpcodetarIn(List<String> values) {
            addCriterion("corpCodeTar in", values, "corpcodetar");
            return (Criteria) this;
        }

        public Criteria andCorpcodetarNotIn(List<String> values) {
            addCriterion("corpCodeTar not in", values, "corpcodetar");
            return (Criteria) this;
        }

        public Criteria andCorpcodetarBetween(String value1, String value2) {
            addCriterion("corpCodeTar between", value1, value2, "corpcodetar");
            return (Criteria) this;
        }

        public Criteria andCorpcodetarNotBetween(String value1, String value2) {
            addCriterion("corpCodeTar not between", value1, value2, "corpcodetar");
            return (Criteria) this;
        }

        public Criteria andCorpnametarIsNull() {
            addCriterion("corpNameTar is null");
            return (Criteria) this;
        }

        public Criteria andCorpnametarIsNotNull() {
            addCriterion("corpNameTar is not null");
            return (Criteria) this;
        }

        public Criteria andCorpnametarEqualTo(String value) {
            addCriterion("corpNameTar =", value, "corpnametar");
            return (Criteria) this;
        }

        public Criteria andCorpnametarNotEqualTo(String value) {
            addCriterion("corpNameTar <>", value, "corpnametar");
            return (Criteria) this;
        }

        public Criteria andCorpnametarGreaterThan(String value) {
            addCriterion("corpNameTar >", value, "corpnametar");
            return (Criteria) this;
        }

        public Criteria andCorpnametarGreaterThanOrEqualTo(String value) {
            addCriterion("corpNameTar >=", value, "corpnametar");
            return (Criteria) this;
        }

        public Criteria andCorpnametarLessThan(String value) {
            addCriterion("corpNameTar <", value, "corpnametar");
            return (Criteria) this;
        }

        public Criteria andCorpnametarLessThanOrEqualTo(String value) {
            addCriterion("corpNameTar <=", value, "corpnametar");
            return (Criteria) this;
        }

        public Criteria andCorpnametarLike(String value) {
            addCriterion("corpNameTar like", value, "corpnametar");
            return (Criteria) this;
        }

        public Criteria andCorpnametarNotLike(String value) {
            addCriterion("corpNameTar not like", value, "corpnametar");
            return (Criteria) this;
        }

        public Criteria andCorpnametarIn(List<String> values) {
            addCriterion("corpNameTar in", values, "corpnametar");
            return (Criteria) this;
        }

        public Criteria andCorpnametarNotIn(List<String> values) {
            addCriterion("corpNameTar not in", values, "corpnametar");
            return (Criteria) this;
        }

        public Criteria andCorpnametarBetween(String value1, String value2) {
            addCriterion("corpNameTar between", value1, value2, "corpnametar");
            return (Criteria) this;
        }

        public Criteria andCorpnametarNotBetween(String value1, String value2) {
            addCriterion("corpNameTar not between", value1, value2, "corpnametar");
            return (Criteria) this;
        }

        public Criteria andCorpshortnametarIsNull() {
            addCriterion("corpShortNameTar is null");
            return (Criteria) this;
        }

        public Criteria andCorpshortnametarIsNotNull() {
            addCriterion("corpShortNameTar is not null");
            return (Criteria) this;
        }

        public Criteria andCorpshortnametarEqualTo(String value) {
            addCriterion("corpShortNameTar =", value, "corpshortnametar");
            return (Criteria) this;
        }

        public Criteria andCorpshortnametarNotEqualTo(String value) {
            addCriterion("corpShortNameTar <>", value, "corpshortnametar");
            return (Criteria) this;
        }

        public Criteria andCorpshortnametarGreaterThan(String value) {
            addCriterion("corpShortNameTar >", value, "corpshortnametar");
            return (Criteria) this;
        }

        public Criteria andCorpshortnametarGreaterThanOrEqualTo(String value) {
            addCriterion("corpShortNameTar >=", value, "corpshortnametar");
            return (Criteria) this;
        }

        public Criteria andCorpshortnametarLessThan(String value) {
            addCriterion("corpShortNameTar <", value, "corpshortnametar");
            return (Criteria) this;
        }

        public Criteria andCorpshortnametarLessThanOrEqualTo(String value) {
            addCriterion("corpShortNameTar <=", value, "corpshortnametar");
            return (Criteria) this;
        }

        public Criteria andCorpshortnametarLike(String value) {
            addCriterion("corpShortNameTar like", value, "corpshortnametar");
            return (Criteria) this;
        }

        public Criteria andCorpshortnametarNotLike(String value) {
            addCriterion("corpShortNameTar not like", value, "corpshortnametar");
            return (Criteria) this;
        }

        public Criteria andCorpshortnametarIn(List<String> values) {
            addCriterion("corpShortNameTar in", values, "corpshortnametar");
            return (Criteria) this;
        }

        public Criteria andCorpshortnametarNotIn(List<String> values) {
            addCriterion("corpShortNameTar not in", values, "corpshortnametar");
            return (Criteria) this;
        }

        public Criteria andCorpshortnametarBetween(String value1, String value2) {
            addCriterion("corpShortNameTar between", value1, value2, "corpshortnametar");
            return (Criteria) this;
        }

        public Criteria andCorpshortnametarNotBetween(String value1, String value2) {
            addCriterion("corpShortNameTar not between", value1, value2, "corpshortnametar");
            return (Criteria) this;
        }

        public Criteria andCorptypetarIsNull() {
            addCriterion("corpTypeTar is null");
            return (Criteria) this;
        }

        public Criteria andCorptypetarIsNotNull() {
            addCriterion("corpTypeTar is not null");
            return (Criteria) this;
        }

        public Criteria andCorptypetarEqualTo(String value) {
            addCriterion("corpTypeTar =", value, "corptypetar");
            return (Criteria) this;
        }

        public Criteria andCorptypetarNotEqualTo(String value) {
            addCriterion("corpTypeTar <>", value, "corptypetar");
            return (Criteria) this;
        }

        public Criteria andCorptypetarGreaterThan(String value) {
            addCriterion("corpTypeTar >", value, "corptypetar");
            return (Criteria) this;
        }

        public Criteria andCorptypetarGreaterThanOrEqualTo(String value) {
            addCriterion("corpTypeTar >=", value, "corptypetar");
            return (Criteria) this;
        }

        public Criteria andCorptypetarLessThan(String value) {
            addCriterion("corpTypeTar <", value, "corptypetar");
            return (Criteria) this;
        }

        public Criteria andCorptypetarLessThanOrEqualTo(String value) {
            addCriterion("corpTypeTar <=", value, "corptypetar");
            return (Criteria) this;
        }

        public Criteria andCorptypetarLike(String value) {
            addCriterion("corpTypeTar like", value, "corptypetar");
            return (Criteria) this;
        }

        public Criteria andCorptypetarNotLike(String value) {
            addCriterion("corpTypeTar not like", value, "corptypetar");
            return (Criteria) this;
        }

        public Criteria andCorptypetarIn(List<String> values) {
            addCriterion("corpTypeTar in", values, "corptypetar");
            return (Criteria) this;
        }

        public Criteria andCorptypetarNotIn(List<String> values) {
            addCriterion("corpTypeTar not in", values, "corptypetar");
            return (Criteria) this;
        }

        public Criteria andCorptypetarBetween(String value1, String value2) {
            addCriterion("corpTypeTar between", value1, value2, "corptypetar");
            return (Criteria) this;
        }

        public Criteria andCorptypetarNotBetween(String value1, String value2) {
            addCriterion("corpTypeTar not between", value1, value2, "corptypetar");
            return (Criteria) this;
        }

        public Criteria andInquiryidIsNull() {
            addCriterion("inquiryId is null");
            return (Criteria) this;
        }

        public Criteria andInquiryidIsNotNull() {
            addCriterion("inquiryId is not null");
            return (Criteria) this;
        }

        public Criteria andInquiryidEqualTo(Integer value) {
            addCriterion("inquiryId =", value, "inquiryid");
            return (Criteria) this;
        }

        public Criteria andInquiryidNotEqualTo(Integer value) {
            addCriterion("inquiryId <>", value, "inquiryid");
            return (Criteria) this;
        }

        public Criteria andInquiryidGreaterThan(Integer value) {
            addCriterion("inquiryId >", value, "inquiryid");
            return (Criteria) this;
        }

        public Criteria andInquiryidGreaterThanOrEqualTo(Integer value) {
            addCriterion("inquiryId >=", value, "inquiryid");
            return (Criteria) this;
        }

        public Criteria andInquiryidLessThan(Integer value) {
            addCriterion("inquiryId <", value, "inquiryid");
            return (Criteria) this;
        }

        public Criteria andInquiryidLessThanOrEqualTo(Integer value) {
            addCriterion("inquiryId <=", value, "inquiryid");
            return (Criteria) this;
        }

        public Criteria andInquiryidIn(List<Integer> values) {
            addCriterion("inquiryId in", values, "inquiryid");
            return (Criteria) this;
        }

        public Criteria andInquiryidNotIn(List<Integer> values) {
            addCriterion("inquiryId not in", values, "inquiryid");
            return (Criteria) this;
        }

        public Criteria andInquiryidBetween(Integer value1, Integer value2) {
            addCriterion("inquiryId between", value1, value2, "inquiryid");
            return (Criteria) this;
        }

        public Criteria andInquiryidNotBetween(Integer value1, Integer value2) {
            addCriterion("inquiryId not between", value1, value2, "inquiryid");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCorpidIsNull() {
            addCriterion("corpId is null");
            return (Criteria) this;
        }

        public Criteria andCorpidIsNotNull() {
            addCriterion("corpId is not null");
            return (Criteria) this;
        }

        public Criteria andCorpidEqualTo(Integer value) {
            addCriterion("corpId =", value, "corpid");
            return (Criteria) this;
        }

        public Criteria andCorpidNotEqualTo(Integer value) {
            addCriterion("corpId <>", value, "corpid");
            return (Criteria) this;
        }

        public Criteria andCorpidGreaterThan(Integer value) {
            addCriterion("corpId >", value, "corpid");
            return (Criteria) this;
        }

        public Criteria andCorpidGreaterThanOrEqualTo(Integer value) {
            addCriterion("corpId >=", value, "corpid");
            return (Criteria) this;
        }

        public Criteria andCorpidLessThan(Integer value) {
            addCriterion("corpId <", value, "corpid");
            return (Criteria) this;
        }

        public Criteria andCorpidLessThanOrEqualTo(Integer value) {
            addCriterion("corpId <=", value, "corpid");
            return (Criteria) this;
        }

        public Criteria andCorpidIn(List<Integer> values) {
            addCriterion("corpId in", values, "corpid");
            return (Criteria) this;
        }

        public Criteria andCorpidNotIn(List<Integer> values) {
            addCriterion("corpId not in", values, "corpid");
            return (Criteria) this;
        }

        public Criteria andCorpidBetween(Integer value1, Integer value2) {
            addCriterion("corpId between", value1, value2, "corpid");
            return (Criteria) this;
        }

        public Criteria andCorpidNotBetween(Integer value1, Integer value2) {
            addCriterion("corpId not between", value1, value2, "corpid");
            return (Criteria) this;
        }

        public Criteria andInquirycontentIsNull() {
            addCriterion("inquiryContent is null");
            return (Criteria) this;
        }

        public Criteria andInquirycontentIsNotNull() {
            addCriterion("inquiryContent is not null");
            return (Criteria) this;
        }

        public Criteria andInquirycontentEqualTo(String value) {
            addCriterion("inquiryContent =", value, "inquirycontent");
            return (Criteria) this;
        }

        public Criteria andInquirycontentNotEqualTo(String value) {
            addCriterion("inquiryContent <>", value, "inquirycontent");
            return (Criteria) this;
        }

        public Criteria andInquirycontentGreaterThan(String value) {
            addCriterion("inquiryContent >", value, "inquirycontent");
            return (Criteria) this;
        }

        public Criteria andInquirycontentGreaterThanOrEqualTo(String value) {
            addCriterion("inquiryContent >=", value, "inquirycontent");
            return (Criteria) this;
        }

        public Criteria andInquirycontentLessThan(String value) {
            addCriterion("inquiryContent <", value, "inquirycontent");
            return (Criteria) this;
        }

        public Criteria andInquirycontentLessThanOrEqualTo(String value) {
            addCriterion("inquiryContent <=", value, "inquirycontent");
            return (Criteria) this;
        }

        public Criteria andInquirycontentLike(String value) {
            addCriterion("inquiryContent like", value, "inquirycontent");
            return (Criteria) this;
        }

        public Criteria andInquirycontentNotLike(String value) {
            addCriterion("inquiryContent not like", value, "inquirycontent");
            return (Criteria) this;
        }

        public Criteria andInquirycontentIn(List<String> values) {
            addCriterion("inquiryContent in", values, "inquirycontent");
            return (Criteria) this;
        }

        public Criteria andInquirycontentNotIn(List<String> values) {
            addCriterion("inquiryContent not in", values, "inquirycontent");
            return (Criteria) this;
        }

        public Criteria andInquirycontentBetween(String value1, String value2) {
            addCriterion("inquiryContent between", value1, value2, "inquirycontent");
            return (Criteria) this;
        }

        public Criteria andInquirycontentNotBetween(String value1, String value2) {
            addCriterion("inquiryContent not between", value1, value2, "inquirycontent");
            return (Criteria) this;
        }

        public Criteria andInquirydateIsNull() {
            addCriterion("inquiryDate is null");
            return (Criteria) this;
        }

        public Criteria andInquirydateIsNotNull() {
            addCriterion("inquiryDate is not null");
            return (Criteria) this;
        }

        public Criteria andInquirydateEqualTo(Date value) {
            addCriterion("inquiryDate =", value, "inquirydate");
            return (Criteria) this;
        }

        public Criteria andInquirydateNotEqualTo(Date value) {
            addCriterion("inquiryDate <>", value, "inquirydate");
            return (Criteria) this;
        }

        public Criteria andInquirydateGreaterThan(Date value) {
            addCriterion("inquiryDate >", value, "inquirydate");
            return (Criteria) this;
        }

        public Criteria andInquirydateGreaterThanOrEqualTo(Date value) {
            addCriterion("inquiryDate >=", value, "inquirydate");
            return (Criteria) this;
        }

        public Criteria andInquirydateLessThan(Date value) {
            addCriterion("inquiryDate <", value, "inquirydate");
            return (Criteria) this;
        }

        public Criteria andInquirydateLessThanOrEqualTo(Date value) {
            addCriterion("inquiryDate <=", value, "inquirydate");
            return (Criteria) this;
        }

        public Criteria andInquirydateIn(List<Date> values) {
            addCriterion("inquiryDate in", values, "inquirydate");
            return (Criteria) this;
        }

        public Criteria andInquirydateNotIn(List<Date> values) {
            addCriterion("inquiryDate not in", values, "inquirydate");
            return (Criteria) this;
        }

        public Criteria andInquirydateBetween(Date value1, Date value2) {
            addCriterion("inquiryDate between", value1, value2, "inquirydate");
            return (Criteria) this;
        }

        public Criteria andInquirydateNotBetween(Date value1, Date value2) {
            addCriterion("inquiryDate not between", value1, value2, "inquirydate");
            return (Criteria) this;
        }

        public Criteria andAttribute1IsNull() {
            addCriterion("attribute1 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute1IsNotNull() {
            addCriterion("attribute1 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute1EqualTo(String value) {
            addCriterion("attribute1 =", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1NotEqualTo(String value) {
            addCriterion("attribute1 <>", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1GreaterThan(String value) {
            addCriterion("attribute1 >", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1GreaterThanOrEqualTo(String value) {
            addCriterion("attribute1 >=", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1LessThan(String value) {
            addCriterion("attribute1 <", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1LessThanOrEqualTo(String value) {
            addCriterion("attribute1 <=", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1Like(String value) {
            addCriterion("attribute1 like", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1NotLike(String value) {
            addCriterion("attribute1 not like", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1In(List<String> values) {
            addCriterion("attribute1 in", values, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1NotIn(List<String> values) {
            addCriterion("attribute1 not in", values, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1Between(String value1, String value2) {
            addCriterion("attribute1 between", value1, value2, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1NotBetween(String value1, String value2) {
            addCriterion("attribute1 not between", value1, value2, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute2IsNull() {
            addCriterion("attribute2 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute2IsNotNull() {
            addCriterion("attribute2 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute2EqualTo(String value) {
            addCriterion("attribute2 =", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2NotEqualTo(String value) {
            addCriterion("attribute2 <>", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2GreaterThan(String value) {
            addCriterion("attribute2 >", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2GreaterThanOrEqualTo(String value) {
            addCriterion("attribute2 >=", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2LessThan(String value) {
            addCriterion("attribute2 <", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2LessThanOrEqualTo(String value) {
            addCriterion("attribute2 <=", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2Like(String value) {
            addCriterion("attribute2 like", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2NotLike(String value) {
            addCriterion("attribute2 not like", value, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2In(List<String> values) {
            addCriterion("attribute2 in", values, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2NotIn(List<String> values) {
            addCriterion("attribute2 not in", values, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2Between(String value1, String value2) {
            addCriterion("attribute2 between", value1, value2, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute2NotBetween(String value1, String value2) {
            addCriterion("attribute2 not between", value1, value2, "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute3IsNull() {
            addCriterion("attribute3 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute3IsNotNull() {
            addCriterion("attribute3 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute3EqualTo(String value) {
            addCriterion("attribute3 =", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3NotEqualTo(String value) {
            addCriterion("attribute3 <>", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3GreaterThan(String value) {
            addCriterion("attribute3 >", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3GreaterThanOrEqualTo(String value) {
            addCriterion("attribute3 >=", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3LessThan(String value) {
            addCriterion("attribute3 <", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3LessThanOrEqualTo(String value) {
            addCriterion("attribute3 <=", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3Like(String value) {
            addCriterion("attribute3 like", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3NotLike(String value) {
            addCriterion("attribute3 not like", value, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3In(List<String> values) {
            addCriterion("attribute3 in", values, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3NotIn(List<String> values) {
            addCriterion("attribute3 not in", values, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3Between(String value1, String value2) {
            addCriterion("attribute3 between", value1, value2, "attribute3");
            return (Criteria) this;
        }

        public Criteria andAttribute3NotBetween(String value1, String value2) {
            addCriterion("attribute3 not between", value1, value2, "attribute3");
            return (Criteria) this;
        }

        public Criteria andCreatedbyIsNull() {
            addCriterion("createdBy is null");
            return (Criteria) this;
        }

        public Criteria andCreatedbyIsNotNull() {
            addCriterion("createdBy is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedbyEqualTo(String value) {
            addCriterion("createdBy =", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyNotEqualTo(String value) {
            addCriterion("createdBy <>", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyGreaterThan(String value) {
            addCriterion("createdBy >", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyGreaterThanOrEqualTo(String value) {
            addCriterion("createdBy >=", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyLessThan(String value) {
            addCriterion("createdBy <", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyLessThanOrEqualTo(String value) {
            addCriterion("createdBy <=", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyLike(String value) {
            addCriterion("createdBy like", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyNotLike(String value) {
            addCriterion("createdBy not like", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyIn(List<String> values) {
            addCriterion("createdBy in", values, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyNotIn(List<String> values) {
            addCriterion("createdBy not in", values, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyBetween(String value1, String value2) {
            addCriterion("createdBy between", value1, value2, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyNotBetween(String value1, String value2) {
            addCriterion("createdBy not between", value1, value2, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreationdateIsNull() {
            addCriterion("creationDate is null");
            return (Criteria) this;
        }

        public Criteria andCreationdateIsNotNull() {
            addCriterion("creationDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreationdateEqualTo(Date value) {
            addCriterion("creationDate =", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateNotEqualTo(Date value) {
            addCriterion("creationDate <>", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateGreaterThan(Date value) {
            addCriterion("creationDate >", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateGreaterThanOrEqualTo(Date value) {
            addCriterion("creationDate >=", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateLessThan(Date value) {
            addCriterion("creationDate <", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateLessThanOrEqualTo(Date value) {
            addCriterion("creationDate <=", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateIn(List<Date> values) {
            addCriterion("creationDate in", values, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateNotIn(List<Date> values) {
            addCriterion("creationDate not in", values, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateBetween(Date value1, Date value2) {
            addCriterion("creationDate between", value1, value2, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateNotBetween(Date value1, Date value2) {
            addCriterion("creationDate not between", value1, value2, "creationdate");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyIsNull() {
            addCriterion("lastUpdateBy is null");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyIsNotNull() {
            addCriterion("lastUpdateBy is not null");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyEqualTo(String value) {
            addCriterion("lastUpdateBy =", value, "lastupdateby");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyNotEqualTo(String value) {
            addCriterion("lastUpdateBy <>", value, "lastupdateby");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyGreaterThan(String value) {
            addCriterion("lastUpdateBy >", value, "lastupdateby");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyGreaterThanOrEqualTo(String value) {
            addCriterion("lastUpdateBy >=", value, "lastupdateby");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyLessThan(String value) {
            addCriterion("lastUpdateBy <", value, "lastupdateby");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyLessThanOrEqualTo(String value) {
            addCriterion("lastUpdateBy <=", value, "lastupdateby");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyLike(String value) {
            addCriterion("lastUpdateBy like", value, "lastupdateby");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyNotLike(String value) {
            addCriterion("lastUpdateBy not like", value, "lastupdateby");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyIn(List<String> values) {
            addCriterion("lastUpdateBy in", values, "lastupdateby");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyNotIn(List<String> values) {
            addCriterion("lastUpdateBy not in", values, "lastupdateby");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyBetween(String value1, String value2) {
            addCriterion("lastUpdateBy between", value1, value2, "lastupdateby");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyNotBetween(String value1, String value2) {
            addCriterion("lastUpdateBy not between", value1, value2, "lastupdateby");
            return (Criteria) this;
        }

        public Criteria andLastupdatedateIsNull() {
            addCriterion("lastUpdateDate is null");
            return (Criteria) this;
        }

        public Criteria andLastupdatedateIsNotNull() {
            addCriterion("lastUpdateDate is not null");
            return (Criteria) this;
        }

        public Criteria andLastupdatedateEqualTo(Date value) {
            addCriterion("lastUpdateDate =", value, "lastupdatedate");
            return (Criteria) this;
        }

        public Criteria andLastupdatedateNotEqualTo(Date value) {
            addCriterion("lastUpdateDate <>", value, "lastupdatedate");
            return (Criteria) this;
        }

        public Criteria andLastupdatedateGreaterThan(Date value) {
            addCriterion("lastUpdateDate >", value, "lastupdatedate");
            return (Criteria) this;
        }

        public Criteria andLastupdatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("lastUpdateDate >=", value, "lastupdatedate");
            return (Criteria) this;
        }

        public Criteria andLastupdatedateLessThan(Date value) {
            addCriterion("lastUpdateDate <", value, "lastupdatedate");
            return (Criteria) this;
        }

        public Criteria andLastupdatedateLessThanOrEqualTo(Date value) {
            addCriterion("lastUpdateDate <=", value, "lastupdatedate");
            return (Criteria) this;
        }

        public Criteria andLastupdatedateIn(List<Date> values) {
            addCriterion("lastUpdateDate in", values, "lastupdatedate");
            return (Criteria) this;
        }

        public Criteria andLastupdatedateNotIn(List<Date> values) {
            addCriterion("lastUpdateDate not in", values, "lastupdatedate");
            return (Criteria) this;
        }

        public Criteria andLastupdatedateBetween(Date value1, Date value2) {
            addCriterion("lastUpdateDate between", value1, value2, "lastupdatedate");
            return (Criteria) this;
        }

        public Criteria andLastupdatedateNotBetween(Date value1, Date value2) {
            addCriterion("lastUpdateDate not between", value1, value2, "lastupdatedate");
            return (Criteria) this;
        }

        public Criteria andCorpcodeLikeInsensitive(String value) {
            addCriterion("upper(corpCode) like", value.toUpperCase(), "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpnameLikeInsensitive(String value) {
            addCriterion("upper(corpName) like", value.toUpperCase(), "corpname");
            return (Criteria) this;
        }

        public Criteria andCorpshortnameLikeInsensitive(String value) {
            addCriterion("upper(corpShortName) like", value.toUpperCase(), "corpshortname");
            return (Criteria) this;
        }

        public Criteria andCorptypeLikeInsensitive(String value) {
            addCriterion("upper(corpType) like", value.toUpperCase(), "corptype");
            return (Criteria) this;
        }

        public Criteria andCorpcodetarLikeInsensitive(String value) {
            addCriterion("upper(corpCodeTar) like", value.toUpperCase(), "corpcodetar");
            return (Criteria) this;
        }

        public Criteria andCorpnametarLikeInsensitive(String value) {
            addCriterion("upper(corpNameTar) like", value.toUpperCase(), "corpnametar");
            return (Criteria) this;
        }

        public Criteria andCorpshortnametarLikeInsensitive(String value) {
            addCriterion("upper(corpShortNameTar) like", value.toUpperCase(), "corpshortnametar");
            return (Criteria) this;
        }

        public Criteria andCorptypetarLikeInsensitive(String value) {
            addCriterion("upper(corpTypeTar) like", value.toUpperCase(), "corptypetar");
            return (Criteria) this;
        }

        public Criteria andInquirycontentLikeInsensitive(String value) {
            addCriterion("upper(inquiryContent) like", value.toUpperCase(), "inquirycontent");
            return (Criteria) this;
        }

        public Criteria andAttribute1LikeInsensitive(String value) {
            addCriterion("upper(attribute1) like", value.toUpperCase(), "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute2LikeInsensitive(String value) {
            addCriterion("upper(attribute2) like", value.toUpperCase(), "attribute2");
            return (Criteria) this;
        }

        public Criteria andAttribute3LikeInsensitive(String value) {
            addCriterion("upper(attribute3) like", value.toUpperCase(), "attribute3");
            return (Criteria) this;
        }

        public Criteria andCreatedbyLikeInsensitive(String value) {
            addCriterion("upper(createdBy) like", value.toUpperCase(), "createdby");
            return (Criteria) this;
        }

        public Criteria andLastupdatebyLikeInsensitive(String value) {
            addCriterion("upper(lastUpdateBy) like", value.toUpperCase(), "lastupdateby");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table v_eqinquiry_target
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table v_eqinquiry_target
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}