package com.test.ado.mapper;

import com.test.vo.entity.JOrgInfoRec;

public interface JOrgInfoRecMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_org_info_rec
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_org_info_rec
     *
     * @mbg.generated
     */
    int insert(JOrgInfoRec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_org_info_rec
     *
     * @mbg.generated
     */
    int insertSelective(JOrgInfoRec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_org_info_rec
     *
     * @mbg.generated
     */
    JOrgInfoRec selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_org_info_rec
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JOrgInfoRec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_org_info_rec
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JOrgInfoRec record);
}