package com.wave.base.vo.entity;

import com.wave.base.vo.BaseVo;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Equote extends BaseVo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUOTE.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUOTE.INQUIRYID
     *
     * @mbg.generated
     */
    private BigDecimal inquiryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUOTE.CORPID
     *
     * @mbg.generated
     */
    private Integer corpid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUOTE.QUOTEDATE
     *
     * @mbg.generated
     */
    private Date quotedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUOTE.RATESEVENDAY
     *
     * @mbg.generated
     */
    private BigDecimal ratesevenday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUOTE.RATEFOURTEENDAY
     *
     * @mbg.generated
     */
    private BigDecimal ratefourteenday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUOTE.RATEONEMONTH
     *
     * @mbg.generated
     */
    private BigDecimal rateonemonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUOTE.RATETWOMONTH
     *
     * @mbg.generated
     */
    private BigDecimal ratetwomonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUOTE.RATETHREEMONTH
     *
     * @mbg.generated
     */
    private BigDecimal ratethreemonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUOTE.RATESIXMONTH
     *
     * @mbg.generated
     */
    private BigDecimal ratesixmonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUOTE.ONEYEAR
     *
     * @mbg.generated
     */
    private BigDecimal oneyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUOTE.QUOTETYPE
     *
     * @mbg.generated
     */
    private String quotetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUOTE.ATTRIBUTE1
     *
     * @mbg.generated
     */
    private String attribute1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUOTE.ATTRIBUTE2
     *
     * @mbg.generated
     */
    private String attribute2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUOTE.ATTRIBUTE3
     *
     * @mbg.generated
     */
    private String attribute3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUOTE.CREATEDBY
     *
     * @mbg.generated
     */
    private String createdby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUOTE.CREATIONDATE
     *
     * @mbg.generated
     */
    private Date creationdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUOTE.LASTUPDATEBY
     *
     * @mbg.generated
     */
    private String lastupdateby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUOTE.LASTUPDATEDATE
     *
     * @mbg.generated
     */
    private Date lastupdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table EQUOTE
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 4934676238107849831L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUOTE.ID
     *
     * @return the value of EQUOTE.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUOTE.ID
     *
     * @param id the value for EQUOTE.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUOTE.INQUIRYID
     *
     * @return the value of EQUOTE.INQUIRYID
     *
     * @mbg.generated
     */
    public BigDecimal getInquiryid() {
        return inquiryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUOTE.INQUIRYID
     *
     * @param inquiryid the value for EQUOTE.INQUIRYID
     *
     * @mbg.generated
     */
    public void setInquiryid(BigDecimal inquiryid) {
        this.inquiryid = inquiryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUOTE.CORPID
     *
     * @return the value of EQUOTE.CORPID
     *
     * @mbg.generated
     */
    public Integer getCorpid() {
        return corpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUOTE.CORPID
     *
     * @param corpid the value for EQUOTE.CORPID
     *
     * @mbg.generated
     */
    public void setCorpid(Integer corpid) {
        this.corpid = corpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUOTE.QUOTEDATE
     *
     * @return the value of EQUOTE.QUOTEDATE
     *
     * @mbg.generated
     */
    public Date getQuotedate() {
        return quotedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUOTE.QUOTEDATE
     *
     * @param quotedate the value for EQUOTE.QUOTEDATE
     *
     * @mbg.generated
     */
    public void setQuotedate(Date quotedate) {
        this.quotedate = quotedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUOTE.RATESEVENDAY
     *
     * @return the value of EQUOTE.RATESEVENDAY
     *
     * @mbg.generated
     */
    public BigDecimal getRatesevenday() {
        return ratesevenday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUOTE.RATESEVENDAY
     *
     * @param ratesevenday the value for EQUOTE.RATESEVENDAY
     *
     * @mbg.generated
     */
    public void setRatesevenday(BigDecimal ratesevenday) {
        this.ratesevenday = ratesevenday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUOTE.RATEFOURTEENDAY
     *
     * @return the value of EQUOTE.RATEFOURTEENDAY
     *
     * @mbg.generated
     */
    public BigDecimal getRatefourteenday() {
        return ratefourteenday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUOTE.RATEFOURTEENDAY
     *
     * @param ratefourteenday the value for EQUOTE.RATEFOURTEENDAY
     *
     * @mbg.generated
     */
    public void setRatefourteenday(BigDecimal ratefourteenday) {
        this.ratefourteenday = ratefourteenday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUOTE.RATEONEMONTH
     *
     * @return the value of EQUOTE.RATEONEMONTH
     *
     * @mbg.generated
     */
    public BigDecimal getRateonemonth() {
        return rateonemonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUOTE.RATEONEMONTH
     *
     * @param rateonemonth the value for EQUOTE.RATEONEMONTH
     *
     * @mbg.generated
     */
    public void setRateonemonth(BigDecimal rateonemonth) {
        this.rateonemonth = rateonemonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUOTE.RATETWOMONTH
     *
     * @return the value of EQUOTE.RATETWOMONTH
     *
     * @mbg.generated
     */
    public BigDecimal getRatetwomonth() {
        return ratetwomonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUOTE.RATETWOMONTH
     *
     * @param ratetwomonth the value for EQUOTE.RATETWOMONTH
     *
     * @mbg.generated
     */
    public void setRatetwomonth(BigDecimal ratetwomonth) {
        this.ratetwomonth = ratetwomonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUOTE.RATETHREEMONTH
     *
     * @return the value of EQUOTE.RATETHREEMONTH
     *
     * @mbg.generated
     */
    public BigDecimal getRatethreemonth() {
        return ratethreemonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUOTE.RATETHREEMONTH
     *
     * @param ratethreemonth the value for EQUOTE.RATETHREEMONTH
     *
     * @mbg.generated
     */
    public void setRatethreemonth(BigDecimal ratethreemonth) {
        this.ratethreemonth = ratethreemonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUOTE.RATESIXMONTH
     *
     * @return the value of EQUOTE.RATESIXMONTH
     *
     * @mbg.generated
     */
    public BigDecimal getRatesixmonth() {
        return ratesixmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUOTE.RATESIXMONTH
     *
     * @param ratesixmonth the value for EQUOTE.RATESIXMONTH
     *
     * @mbg.generated
     */
    public void setRatesixmonth(BigDecimal ratesixmonth) {
        this.ratesixmonth = ratesixmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUOTE.ONEYEAR
     *
     * @return the value of EQUOTE.ONEYEAR
     *
     * @mbg.generated
     */
    public BigDecimal getOneyear() {
        return oneyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUOTE.ONEYEAR
     *
     * @param oneyear the value for EQUOTE.ONEYEAR
     *
     * @mbg.generated
     */
    public void setOneyear(BigDecimal oneyear) {
        this.oneyear = oneyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUOTE.QUOTETYPE
     *
     * @return the value of EQUOTE.QUOTETYPE
     *
     * @mbg.generated
     */
    public String getQuotetype() {
        return quotetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUOTE.QUOTETYPE
     *
     * @param quotetype the value for EQUOTE.QUOTETYPE
     *
     * @mbg.generated
     */
    public void setQuotetype(String quotetype) {
        this.quotetype = quotetype == null ? null : quotetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUOTE.ATTRIBUTE1
     *
     * @return the value of EQUOTE.ATTRIBUTE1
     *
     * @mbg.generated
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUOTE.ATTRIBUTE1
     *
     * @param attribute1 the value for EQUOTE.ATTRIBUTE1
     *
     * @mbg.generated
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1 == null ? null : attribute1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUOTE.ATTRIBUTE2
     *
     * @return the value of EQUOTE.ATTRIBUTE2
     *
     * @mbg.generated
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUOTE.ATTRIBUTE2
     *
     * @param attribute2 the value for EQUOTE.ATTRIBUTE2
     *
     * @mbg.generated
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2 == null ? null : attribute2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUOTE.ATTRIBUTE3
     *
     * @return the value of EQUOTE.ATTRIBUTE3
     *
     * @mbg.generated
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUOTE.ATTRIBUTE3
     *
     * @param attribute3 the value for EQUOTE.ATTRIBUTE3
     *
     * @mbg.generated
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3 == null ? null : attribute3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUOTE.CREATEDBY
     *
     * @return the value of EQUOTE.CREATEDBY
     *
     * @mbg.generated
     */
    public String getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUOTE.CREATEDBY
     *
     * @param createdby the value for EQUOTE.CREATEDBY
     *
     * @mbg.generated
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby == null ? null : createdby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUOTE.CREATIONDATE
     *
     * @return the value of EQUOTE.CREATIONDATE
     *
     * @mbg.generated
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUOTE.CREATIONDATE
     *
     * @param creationdate the value for EQUOTE.CREATIONDATE
     *
     * @mbg.generated
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUOTE.LASTUPDATEBY
     *
     * @return the value of EQUOTE.LASTUPDATEBY
     *
     * @mbg.generated
     */
    public String getLastupdateby() {
        return lastupdateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUOTE.LASTUPDATEBY
     *
     * @param lastupdateby the value for EQUOTE.LASTUPDATEBY
     *
     * @mbg.generated
     */
    public void setLastupdateby(String lastupdateby) {
        this.lastupdateby = lastupdateby == null ? null : lastupdateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUOTE.LASTUPDATEDATE
     *
     * @return the value of EQUOTE.LASTUPDATEDATE
     *
     * @mbg.generated
     */
    public Date getLastupdatedate() {
        return lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUOTE.LASTUPDATEDATE
     *
     * @param lastupdatedate the value for EQUOTE.LASTUPDATEDATE
     *
     * @mbg.generated
     */
    public void setLastupdatedate(Date lastupdatedate) {
        this.lastupdatedate = lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUOTE
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Equote other = (Equote) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getInquiryid() == null ? other.getInquiryid() == null : this.getInquiryid().equals(other.getInquiryid()))
            && (this.getCorpid() == null ? other.getCorpid() == null : this.getCorpid().equals(other.getCorpid()))
            && (this.getQuotedate() == null ? other.getQuotedate() == null : this.getQuotedate().equals(other.getQuotedate()))
            && (this.getRatesevenday() == null ? other.getRatesevenday() == null : this.getRatesevenday().equals(other.getRatesevenday()))
            && (this.getRatefourteenday() == null ? other.getRatefourteenday() == null : this.getRatefourteenday().equals(other.getRatefourteenday()))
            && (this.getRateonemonth() == null ? other.getRateonemonth() == null : this.getRateonemonth().equals(other.getRateonemonth()))
            && (this.getRatetwomonth() == null ? other.getRatetwomonth() == null : this.getRatetwomonth().equals(other.getRatetwomonth()))
            && (this.getRatethreemonth() == null ? other.getRatethreemonth() == null : this.getRatethreemonth().equals(other.getRatethreemonth()))
            && (this.getRatesixmonth() == null ? other.getRatesixmonth() == null : this.getRatesixmonth().equals(other.getRatesixmonth()))
            && (this.getOneyear() == null ? other.getOneyear() == null : this.getOneyear().equals(other.getOneyear()))
            && (this.getQuotetype() == null ? other.getQuotetype() == null : this.getQuotetype().equals(other.getQuotetype()))
            && (this.getAttribute1() == null ? other.getAttribute1() == null : this.getAttribute1().equals(other.getAttribute1()))
            && (this.getAttribute2() == null ? other.getAttribute2() == null : this.getAttribute2().equals(other.getAttribute2()))
            && (this.getAttribute3() == null ? other.getAttribute3() == null : this.getAttribute3().equals(other.getAttribute3()))
            && (this.getCreatedby() == null ? other.getCreatedby() == null : this.getCreatedby().equals(other.getCreatedby()))
            && (this.getCreationdate() == null ? other.getCreationdate() == null : this.getCreationdate().equals(other.getCreationdate()))
            && (this.getLastupdateby() == null ? other.getLastupdateby() == null : this.getLastupdateby().equals(other.getLastupdateby()))
            && (this.getLastupdatedate() == null ? other.getLastupdatedate() == null : this.getLastupdatedate().equals(other.getLastupdatedate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUOTE
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getInquiryid() == null) ? 0 : getInquiryid().hashCode());
        result = prime * result + ((getCorpid() == null) ? 0 : getCorpid().hashCode());
        result = prime * result + ((getQuotedate() == null) ? 0 : getQuotedate().hashCode());
        result = prime * result + ((getRatesevenday() == null) ? 0 : getRatesevenday().hashCode());
        result = prime * result + ((getRatefourteenday() == null) ? 0 : getRatefourteenday().hashCode());
        result = prime * result + ((getRateonemonth() == null) ? 0 : getRateonemonth().hashCode());
        result = prime * result + ((getRatetwomonth() == null) ? 0 : getRatetwomonth().hashCode());
        result = prime * result + ((getRatethreemonth() == null) ? 0 : getRatethreemonth().hashCode());
        result = prime * result + ((getRatesixmonth() == null) ? 0 : getRatesixmonth().hashCode());
        result = prime * result + ((getOneyear() == null) ? 0 : getOneyear().hashCode());
        result = prime * result + ((getQuotetype() == null) ? 0 : getQuotetype().hashCode());
        result = prime * result + ((getAttribute1() == null) ? 0 : getAttribute1().hashCode());
        result = prime * result + ((getAttribute2() == null) ? 0 : getAttribute2().hashCode());
        result = prime * result + ((getAttribute3() == null) ? 0 : getAttribute3().hashCode());
        result = prime * result + ((getCreatedby() == null) ? 0 : getCreatedby().hashCode());
        result = prime * result + ((getCreationdate() == null) ? 0 : getCreationdate().hashCode());
        result = prime * result + ((getLastupdateby() == null) ? 0 : getLastupdateby().hashCode());
        result = prime * result + ((getLastupdatedate() == null) ? 0 : getLastupdatedate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUOTE
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", inquiryid=").append(inquiryid);
        sb.append(", corpid=").append(corpid);
        sb.append(", quotedate=").append(quotedate);
        sb.append(", ratesevenday=").append(ratesevenday);
        sb.append(", ratefourteenday=").append(ratefourteenday);
        sb.append(", rateonemonth=").append(rateonemonth);
        sb.append(", ratetwomonth=").append(ratetwomonth);
        sb.append(", ratethreemonth=").append(ratethreemonth);
        sb.append(", ratesixmonth=").append(ratesixmonth);
        sb.append(", oneyear=").append(oneyear);
        sb.append(", quotetype=").append(quotetype);
        sb.append(", attribute1=").append(attribute1);
        sb.append(", attribute2=").append(attribute2);
        sb.append(", attribute3=").append(attribute3);
        sb.append(", createdby=").append(createdby);
        sb.append(", creationdate=").append(creationdate);
        sb.append(", lastupdateby=").append(lastupdateby);
        sb.append(", lastupdatedate=").append(lastupdatedate);
        sb.append("]");
        return sb.toString();
    }
}