package com.wave.base.dao.mapper;

import com.wave.base.vo.entity.Eqinquiry;
import com.wave.base.vo.entity.EqinquiryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EqinquiryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQINQUIRY
     *
     * @mbg.generated
     */
    long countByExample(EqinquiryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQINQUIRY
     *
     * @mbg.generated
     */
    int deleteByExample(EqinquiryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQINQUIRY
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQINQUIRY
     *
     * @mbg.generated
     */
    int insert(Eqinquiry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQINQUIRY
     *
     * @mbg.generated
     */
    int insertSelective(Eqinquiry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQINQUIRY
     *
     * @mbg.generated
     */
    List<Eqinquiry> selectByExample(EqinquiryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQINQUIRY
     *
     * @mbg.generated
     */
    Eqinquiry selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQINQUIRY
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Eqinquiry record, @Param("example") EqinquiryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQINQUIRY
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Eqinquiry record, @Param("example") EqinquiryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQINQUIRY
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Eqinquiry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQINQUIRY
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Eqinquiry record);
}