package com.wave.base.dao.mapper;

import com.wave.base.vo.entity.Syscorpfiles;
import com.wave.base.vo.entity.SyscorpfilesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SyscorpfilesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCORPFILES
     *
     * @mbg.generated
     */
    long countByExample(SyscorpfilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCORPFILES
     *
     * @mbg.generated
     */
    int deleteByExample(SyscorpfilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCORPFILES
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCORPFILES
     *
     * @mbg.generated
     */
    int insert(Syscorpfiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCORPFILES
     *
     * @mbg.generated
     */
    int insertSelective(Syscorpfiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCORPFILES
     *
     * @mbg.generated
     */
    List<Syscorpfiles> selectByExample(SyscorpfilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCORPFILES
     *
     * @mbg.generated
     */
    Syscorpfiles selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCORPFILES
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Syscorpfiles record, @Param("example") SyscorpfilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCORPFILES
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Syscorpfiles record, @Param("example") SyscorpfilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCORPFILES
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Syscorpfiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSCORPFILES
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Syscorpfiles record);
}