package com.wave.base.dao.mapper;

import com.wave.base.vo.entity.VEqinquiryTarget;
import com.wave.base.vo.entity.VEqinquiryTargetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VEqinquiryTargetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_eqinquiry_target
     *
     * @mbg.generated
     */
    long countByExample(VEqinquiryTargetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_eqinquiry_target
     *
     * @mbg.generated
     */
    int deleteByExample(VEqinquiryTargetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_eqinquiry_target
     *
     * @mbg.generated
     */
    int insert(VEqinquiryTarget record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_eqinquiry_target
     *
     * @mbg.generated
     */
    int insertSelective(VEqinquiryTarget record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_eqinquiry_target
     *
     * @mbg.generated
     */
    List<VEqinquiryTarget> selectByExample(VEqinquiryTargetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_eqinquiry_target
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VEqinquiryTarget record, @Param("example") VEqinquiryTargetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_eqinquiry_target
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VEqinquiryTarget record, @Param("example") VEqinquiryTargetExample example);
}