package com.wave.base.dao.mapper;

import com.wave.base.vo.entity.Equotetarget;
import com.wave.base.vo.entity.EquotetargetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EquotetargetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUOTETARGET
     *
     * @mbg.generated
     */
    long countByExample(EquotetargetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUOTETARGET
     *
     * @mbg.generated
     */
    int deleteByExample(EquotetargetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUOTETARGET
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUOTETARGET
     *
     * @mbg.generated
     */
    int insert(Equotetarget record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUOTETARGET
     *
     * @mbg.generated
     */
    int insertSelective(Equotetarget record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUOTETARGET
     *
     * @mbg.generated
     */
    List<Equotetarget> selectByExample(EquotetargetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUOTETARGET
     *
     * @mbg.generated
     */
    Equotetarget selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUOTETARGET
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Equotetarget record, @Param("example") EquotetargetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUOTETARGET
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Equotetarget record, @Param("example") EquotetargetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUOTETARGET
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Equotetarget record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUOTETARGET
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Equotetarget record);
}