package com.wave.base.dao.mapper;

import com.wave.base.vo.entity.Equote;
import com.wave.base.vo.entity.EquoteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EquoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUOTE
     *
     * @mbg.generated
     */
    long countByExample(EquoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUOTE
     *
     * @mbg.generated
     */
    int deleteByExample(EquoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUOTE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUOTE
     *
     * @mbg.generated
     */
    int insert(Equote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUOTE
     *
     * @mbg.generated
     */
    int insertSelective(Equote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUOTE
     *
     * @mbg.generated
     */
    List<Equote> selectByExample(EquoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUOTE
     *
     * @mbg.generated
     */
    Equote selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUOTE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Equote record, @Param("example") EquoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUOTE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Equote record, @Param("example") EquoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUOTE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Equote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EQUOTE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Equote record);
}