package com.test.ado.mapper;

import com.test.vo.entity.JInnerOrgRec;

public interface JInnerOrgRecMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table j_inner_org_rec
	 * @mbg.generated
	 */
	int insert(JInnerOrgRec record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table j_inner_org_rec
	 * @mbg.generated
	 */
	int insertSelective(JInnerOrgRec record);
}